// Code generated by candi v1.20.0. DO NOT EDIT.

package repository

import (
	"go.mongodb.org/mongo-driver/v2/mongo"

	// @candi:repositoryImport
	activityrepo "monorepo/services/activity/internal/modules/activity/repository"
)

type (
	// RepoMongo abstraction
	RepoMongo interface {
		// @candi:repositoryMethod
		ActivityRepo() activityrepo.ActivityRepository
	}

	repoMongoImpl struct {
		readDB, writeDB *mongo.Database

		// register all repository from modules
		// @candi:repositoryField
		activityRepo activityrepo.ActivityRepository
	}
)

var globalRepoMongo RepoMongo

// setSharedRepoMongo set the global singleton "RepoMongo" implementation
func setSharedRepoMongo(readDB, writeDB *mongo.Database) {
	globalRepoMongo = &repoMongoImpl{
		readDB: readDB, writeDB: writeDB,

		// @candi:repositoryConstructor
		activityRepo: activityrepo.NewActivityRepoMongo(readDB, writeDB),
	}
}

// GetSharedRepoMongo returns the global singleton "RepoMongo" implementation
func GetSharedRepoMongo() RepoMongo {
	return globalRepoMongo
}

// @candi:repositoryImplementation
func (r *repoMongoImpl) ActivityRepo() activityrepo.ActivityRepository {
	return r.activityRepo
}
