// Code generated by candi v1.20.0.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	notificationusecase "monorepo/services/notification/internal/modules/notification/usecase"
	"monorepo/services/notification/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		Notification() notificationusecase.NotificationUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		notificationusecase.NotificationUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.NotificationUsecase, setSharedUsecaseFunc = notificationusecase.NewNotificationUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) Notification() notificationusecase.NotificationUsecase {
	return uc.NotificationUsecase
}
