// Code generated by candi v1.20.0.

package payment

import (
	"monorepo/services/payment/internal/modules/gateway"
	"monorepo/services/payment/internal/modules/method"
	"monorepo/services/payment/internal/modules/payment"
	"monorepo/services/payment/internal/modules/topic"

	"monorepo/services/payment/configs"
	"monorepo/services/payment/internal/modules/payment/delivery/workerhandler"
	"monorepo/services/payment/pkg/shared"

	"github.com/golangid/candi/codebase/factory"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/factory/types"
	"github.com/golangid/candi/config"
)

// Service model
type Service struct {
	cfg          *config.Config
	deps         dependency.Dependency
	applications []factory.AppServerFactory
	modules      []factory.ModuleFactory
	name         types.Service
}

// NewService in this service
func NewService(cfg *config.Config) factory.ServiceFactory {
	deps := configs.LoadServiceConfigs(cfg)

	modules := []factory.ModuleFactory{
		payment.NewModule(deps),
		gateway.NewModule(deps),
		method.NewModule(deps),
		topic.NewModule(deps),
	}

	s := &Service{
		cfg:     cfg,
		deps:    deps,
		modules: modules,
		name:    types.Service(cfg.ServiceName),
	}

	s.applications = configs.InitAppFromEnvironmentConfig(s)

	// gateway callbacks: Kafka topics are read from the DB and hot-reloaded (see the payment module's workerhandler)
	if shared.GetEnv().UseCallbackConsumer {
		s.applications = append(s.applications, workerhandler.NewCallbackConsumer(s))
	}

	// Add custom application runner, must implement `factory.AppServerFactory` methods
	s.applications = append(s.applications, []factory.AppServerFactory{
		// customApplication
	}...)

	return s
}

// GetConfig method
func (s *Service) GetConfig() *config.Config {
	return s.cfg
}

// GetDependency method
func (s *Service) GetDependency() dependency.Dependency {
	return s.deps
}

// GetApplications method
func (s *Service) GetApplications() []factory.AppServerFactory {
	return s.applications
}

// GetModules method
func (s *Service) GetModules() []factory.ModuleFactory {
	return s.modules
}

// Name method
func (s *Service) Name() types.Service {
	return s.name
}
