# UserModule Resolver Area
type UserQueryResolver {
	getAllUser(realm: String!, filter: FilterListInputResolver): UserListResolver! @permissionACL(permissionCode: getAllUser)
	getDetailUser(realm: String!, id: Int!): UserResolver! @permissionACL(permissionCode: getDetailUser)
	getUserRoles(realm: String!, userId: Int!): [UserRoleResolver!]! @permissionACL(permissionCode: getUserRoles)
}

type UserMutationResolver {
	createUser(realm: String!, data: UserCreateInputResolver!): UserResolver! @permissionACL(permissionCode: createUser)
	updateUser(realm: String!, id: Int!, data: UserUpdateInputResolver!): String! @permissionACL(permissionCode: updateUser)
	deleteUser(realm: String!, id: Int!): String! @permissionACL(permissionCode: deleteUser)
	setUserPassword(realm: String!, id: Int!, password: String!): String! @permissionACL(permissionCode: setUserPassword)
	unlockUser(realm: String!, id: Int!): String! @permissionACL(permissionCode: unlockUser)
	addUserRole(realm: String!, userId: Int!, roleId: Int!): String! @permissionACL(permissionCode: addUserRole)
	replaceUserRoles(realm: String!, userId: Int!, roleIds: [Int!]!): String! @permissionACL(permissionCode: replaceUserRoles)
	removeUserRole(realm: String!, userId: Int!, roleId: Int!): String! @permissionACL(permissionCode: removeUserRole)
}

type UserListResolver {
	meta: MetaResolver!
	data: [UserResolver!]!
}

type UserRoleResolver {
	id: Int!
	name: String!
	description: String!
}

type UserResolver {
	id: Int!
	username: String!
	email: String!
	phone: String!
	fullName: String!
	status: String!
	lockedUntil: String!
	lastLoginAt: String!
	isServiceAccount: Boolean!
	roles: [UserRoleResolver!]!
	createdAt: String!
	updatedAt: String!
}

input UserCreateInputResolver {
	username: String!
	email: String!
	phone: String!
	fullName: String!
	password: String!
	"active (default) or disabled"
	status: String!
	roleIds: [Int!]!
}

input UserUpdateInputResolver {
	username: String!
	email: String!
	phone: String!
	fullName: String!
	"active or disabled"
	status: String!
}
