// Code generated by candi v1.20.0.

package usecase

import (
	"context"

	"monorepo/services/notification/internal/modules/notification/channel"
	"monorepo/services/notification/internal/modules/notification/domain"
	"monorepo/services/notification/pkg/shared/repository"
	"monorepo/services/notification/pkg/shared/usecase/common"

	taskqueueworker "github.com/golangid/candi/codebase/app/task_queue_worker"
	"github.com/golangid/candi/codebase/factory/dependency"
)

// NotificationUsecase abstraction
type NotificationUsecase interface {
	// SendNotification renders the template and enqueues an async dispatch
	// job, returning immediately (REST/Kafka/cross-module entrypoint).
	SendNotification(ctx context.Context, req *domain.RequestSendNotification) (jobID string, err error)
	// DispatchNotification does the actual send via the channel's Sender.
	// Called only from the task queue worker handler.
	DispatchNotification(ctx context.Context, payload *domain.DispatchPayload) (err error)

	CreateTemplate(ctx context.Context, req *domain.RequestUpsertTemplate) (res domain.ResponseTemplate, err error)
	UpdateTemplate(ctx context.Context, id int, req *domain.RequestUpsertTemplate) (res domain.ResponseTemplate, err error)
	GetAllTemplates(ctx context.Context, filter *domain.FilterTemplate) (data domain.ResponseTemplateList, err error)
	DeleteTemplate(ctx context.Context, id int) (err error)

	GetChannelConfig(ctx context.Context, channel string) (res domain.ResponseChannelConfig, err error)
	UpdateChannelConfig(ctx context.Context, channel string, req *domain.RequestUpsertChannelConfig) (res domain.ResponseChannelConfig, err error)

	GetAllNotificationLogs(ctx context.Context, filter *domain.FilterNotificationLog) (data domain.ResponseNotificationLogList, err error)
	GetNotificationLogByID(ctx context.Context, id int) (data domain.ResponseNotificationLog, err error)
}

type notificationUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL

	senders map[string]channel.Sender

	// jobEnqueuer wraps taskqueueworker.AddJob so it can be swapped out in tests.
	jobEnqueuer func(ctx context.Context, req *taskqueueworker.AddJobRequest) (string, error)
}

// NewNotificationUsecase usecase impl constructor
func NewNotificationUsecase(deps dependency.Dependency) (NotificationUsecase, func(sharedUsecase common.Usecase)) {
	uc := &notificationUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
		senders: map[string]channel.Sender{
			domain.ChannelEmail: channel.NewEmailSender(),
			domain.ChannelPush:  channel.NewPushSender(),
		},
		jobEnqueuer: taskqueueworker.AddJob,
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
