// Code generated by candi v1.20.0.

package repository

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"

	"monorepo/services/activity/internal/modules/activity/domain"
	shareddomain "monorepo/services/activity/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"
)

type activityRepoMongo struct {
	readDB, writeDB *mongo.Database
	collection      string
	updateTools     *candishared.DBUpdateTools
}

// NewActivityRepoMongo mongo repo constructor
func NewActivityRepoMongo(readDB, writeDB *mongo.Database) ActivityRepository {
	return &activityRepoMongo{
		readDB: 	readDB, 
		writeDB: 	writeDB, 
		collection: shareddomain.Activity{}.CollectionName(),
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateMongoExtractorKey,
			IgnoredFields:    []string{"_id"},
		},
	}
}

func (r *activityRepoMongo) FetchAll(ctx context.Context, filter *domain.FilterActivity) (data []shareddomain.Activity, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoMongo:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	query := r.setFilterActivity(filter)
	trace.Log("query", query)

	findOptions := options.Find()
	sort := bson.D{}
	if len(filter.OrderBy) == 0 {
		filter.OrderBy = "updated_at"
	}
	s := -1
	if filter.Sort == "ASC" {
		s = 1
	}
	sort = append(sort, bson.E{Key: filter.OrderBy, Value: s})
	findOptions.SetSort(sort)

	if !filter.ShowAll {
		findOptions.SetLimit(int64(filter.Limit))
		findOptions.SetSkip(int64(filter.CalculateOffset()))
	}
	cur, err := r.readDB.Collection(r.collection).Find(ctx, query, findOptions)
	if err != nil {
		return nil, err
	}
	defer cur.Close(ctx)

	err = cur.All(ctx, &data)
	return
}

func (r *activityRepoMongo) Find(ctx context.Context, filter *domain.FilterActivity) (result shareddomain.Activity, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoMongo:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	query := r.setFilterActivity(filter)
	trace.Log("query", query)

	err = r.readDB.Collection(r.collection).FindOne(ctx, query).Decode(&result)
	return
}

func (r *activityRepoMongo) Count(ctx context.Context, filter *domain.FilterActivity) int {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoMongo:Count")
	defer trace.Finish()

	query := r.setFilterActivity(filter)
	trace.Log("query", query)

	count, err := r.readDB.Collection(r.collection).CountDocuments(ctx, query)
	trace.SetError(err)
	return int(count)
}

func (r *activityRepoMongo) Save(ctx context.Context, data *shareddomain.Activity, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoMongo:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	data.UpdatedAt = time.Now()
	if data.ID.IsZero() {
		data.ID = bson.NewObjectID()
		data.CreatedAt = time.Now()
		_, err = r.writeDB.Collection(r.collection).InsertOne(ctx, data)
		trace.Log("data", data)

	} else {
		updated := r.updateTools.ToMap(data, updateOptions...)
		trace.Log("updated", updated)
		opt := options.UpdateOne().SetUpsert(true)
		_, err = r.writeDB.Collection(r.collection).UpdateOne(ctx,
			bson.D{{Key: "_id", Value: data.ID}},
			bson.D{{Key: "$set", Value: updated}}, opt)
	}

	trace.SetTag("id", data.ID.Hex())
	return
}

func (r *activityRepoMongo) Delete(ctx context.Context, filter *domain.FilterActivity) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoMongo:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	_, err = r.writeDB.Collection(r.collection).DeleteOne(ctx, r.setFilterActivity(filter))
	return
}

func (r *activityRepoMongo) setFilterActivity(filter *domain.FilterActivity) bson.D {

	query := bson.D{}

	if filter.ID != nil {
		id, _ := bson.ObjectIDFromHex(*filter.ID)
		query = append(query, bson.E{Key: "_id", Value: id})
	}
	if filter.ServiceName != "" {
		query = append(query, bson.E{Key: "service_name", Value: filter.ServiceName})
	}
	if filter.ReferenceID != "" {
		query = append(query, bson.E{Key: "reference_id", Value: filter.ReferenceID})
	}
	if filter.Search != "" {
		query = append(query, bson.E{Key: "message", Value: bson.D{{Key: "$regex", Value: filter.Search}}})
	}
	if filter.StartDate != "" || filter.EndDate != "" {
		dateRange := bson.D{}
		if filter.StartDate != "" {
			if t, err := time.Parse(time.RFC3339, filter.StartDate); err == nil {
				dateRange = append(dateRange, bson.E{Key: "$gte", Value: t})
			}
		}
		if filter.EndDate != "" {
			if t, err := time.Parse(time.RFC3339, filter.EndDate); err == nil {
				dateRange = append(dateRange, bson.E{Key: "$lte", Value: t})
			}
		}
		if len(dateRange) > 0 {
			query = append(query, bson.E{Key: "created_at", Value: dateRange})
		}
	}

	return query
}
