// Code generated by candi v1.20.0.

package repository

import (
	"context"
	"database/sql"
	"fmt"

	// @candi:repositoryImport
	exportrepo "monorepo/services/order/internal/modules/export/repository"
	invoicerepo "monorepo/services/order/internal/modules/invoice/repository"
	merchantrepo "monorepo/services/order/internal/modules/merchant/repository"
	orderrepo "monorepo/services/order/internal/modules/order/repository"
	shiftrepo "monorepo/services/order/internal/modules/shift/repository"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"monorepo/globalshared"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

type (
	// RepoSQL abstraction
	RepoSQL interface {
		WithTransaction(ctx context.Context, txFunc func(ctx context.Context) error) (err error)

		// @candi:repositoryMethod
		OrderRepo() orderrepo.OrderRepository
		InvoiceRepo() invoicerepo.InvoiceRepository
		MerchantRepo() merchantrepo.MerchantRepository
		ShiftRepo() shiftrepo.ShiftRepository
		ExportRepo() exportrepo.ExportRepository

		// shared by several modules
		SequenceRepo() SequenceRepository
		OutboxRepo() OutboxRepository
	}

	repoSQLImpl struct {
		readDB, writeDB *gorm.DB

		// register all repository from modules
		// @candi:repositoryField
		orderRepo    orderrepo.OrderRepository
		invoiceRepo  invoicerepo.InvoiceRepository
		merchantRepo merchantrepo.MerchantRepository
		shiftRepo    shiftrepo.ShiftRepository
		exportRepo   exportrepo.ExportRepository
		sequenceRepo SequenceRepository
		outboxRepo   OutboxRepository
	}
)

var (
	globalRepoSQL RepoSQL
)

// setSharedRepoSQL set the global singleton "RepoSQL" implementation
func setSharedRepoSQL(readDB, writeDB *sql.DB) {
	gormRead, err := gorm.Open(postgres.New(postgres.Config{
		Conn: readDB,
	}), &gorm.Config{})
	if err != nil {
		panic(err)
	}

	gormWrite, err := gorm.Open(postgres.New(postgres.Config{
		Conn: writeDB,
	}), &gorm.Config{SkipDefaultTransaction: true})
	if err != nil {
		panic(err)
	}

	globalshared.AddGormCallbacks(gormRead)
	globalshared.AddGormCallbacks(gormWrite)

	globalRepoSQL = NewRepositorySQL(gormRead, gormWrite)
}

// GetSharedRepoSQL returns the global singleton "RepoSQL" implementation
func GetSharedRepoSQL() RepoSQL {
	return globalRepoSQL
}

// NewRepositorySQL constructor
func NewRepositorySQL(readDB, writeDB *gorm.DB) RepoSQL {

	return &repoSQLImpl{
		readDB: readDB, writeDB: writeDB,

		// @candi:repositoryConstructor
		orderRepo:    orderrepo.NewOrderRepoSQL(readDB, writeDB),
		invoiceRepo:  invoicerepo.NewInvoiceRepoSQL(readDB, writeDB),
		merchantRepo: merchantrepo.NewMerchantRepoSQL(readDB, writeDB),
		shiftRepo:    shiftrepo.NewShiftRepoSQL(readDB, writeDB),
		exportRepo:   exportrepo.NewExportRepoSQL(readDB, writeDB),
		sequenceRepo: &sequenceRepoSQL{db: writeDB},
		outboxRepo:   &outboxRepoSQL{db: writeDB},
	}
}

// WithTransaction run transaction for each repository with context, include handle canceled or timeout context
func (r *repoSQLImpl) WithTransaction(ctx context.Context, txFunc func(ctx context.Context) error) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "RepoSQL:Transaction")
	defer trace.Finish()

	tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB)
	if !ok {
		tx = r.writeDB.Begin()
		if tx.Error != nil {
			return tx.Error
		}

		defer func() {
			if err != nil {
				tx.Rollback()
				trace.SetError(err)
			} else {
				tx.Commit()
			}
		}()
		ctx = candishared.SetToContext(ctx, candishared.ContextKeySQLTransaction, tx)
	}

	errChan := make(chan error)
	go func(ctx context.Context) {
		defer func() {
			if r := recover(); r != nil {
				errChan <- fmt.Errorf("panic: %v", r)
			}
			close(errChan)
		}()

		if err := txFunc(ctx); err != nil {
			errChan <- err
		}
	}(ctx)

	select {
	case <-ctx.Done():
		return fmt.Errorf("Canceled or timeout: %v", ctx.Err())
	case e := <-errChan:
		return e
	}
}

// @candi:repositoryImplementation
func (r *repoSQLImpl) OrderRepo() orderrepo.OrderRepository {
	return r.orderRepo
}

func (r *repoSQLImpl) InvoiceRepo() invoicerepo.InvoiceRepository {
	return r.invoiceRepo
}

func (r *repoSQLImpl) MerchantRepo() merchantrepo.MerchantRepository {
	return r.merchantRepo
}

func (r *repoSQLImpl) ShiftRepo() shiftrepo.ShiftRepository {
	return r.shiftRepo
}

func (r *repoSQLImpl) ExportRepo() exportrepo.ExportRepository {
	return r.exportRepo
}

// SequenceRepo gapless number sequences
func (r *repoSQLImpl) SequenceRepo() SequenceRepository {
	return r.sequenceRepo
}

// OutboxRepo transactional outbox
func (r *repoSQLImpl) OutboxRepo() OutboxRepository {
	return r.outboxRepo
}
