// Code generated by candi v1.20.0.

package usecase

import (
	"context"

	"monorepo/services/notification/internal/modules/otp/domain"
	"monorepo/services/notification/pkg/shared/repository"
	"monorepo/services/notification/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// OtpUsecase abstraction
type OtpUsecase interface {
	// RequestOTP generates a code, stores it hashed, and asks the
	// notification module to deliver it — returns the underlying send job ID.
	RequestOTP(ctx context.Context, req *domain.RequestOTP) (jobID string, err error)
	// VerifyOTP checks a submitted code against the latest unverified request.
	VerifyOTP(ctx context.Context, req *domain.RequestVerifyOTP) (verified bool, err error)
}

type otpUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
}

// NewOtpUsecase usecase impl constructor
func NewOtpUsecase(deps dependency.Dependency) (OtpUsecase, func(sharedUsecase common.Usecase)) {
	uc := &otpUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
