package resthandler

import (
	"io"
	"net/http"
	"strconv"

	"monorepo/globalshared/auth"
	"monorepo/globalshared/rest"
	"monorepo/services/order/internal/modules/export/domain"
	ucexport "monorepo/services/order/internal/modules/export/usecase"
	"monorepo/services/order/pkg/shared"
	"monorepo/services/order/pkg/shared/usecase"

	restserver "github.com/golangid/candi/codebase/app/rest_server"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator()}
}

// Mount handler with root "/". Routes are registered flat, see the user service for why.
// An export is requested, generated by the task queue worker, then downloaded. Callers see their
// own exports; manageExports sees everybody's.
func (h *RestHandler) Mount(root interfaces.RESTRouter) {
	// the permission depends on the export type, checked in the handler
	root.POST("/v1/exports", h.create, h.mw.HTTPBearerAuth)
	root.GET("/v1/exports", h.getAll, rest.Secure(h.mw, "getExports")...)
	root.GET("/v1/exports/:id", h.get, rest.Secure(h.mw, "getExports")...)
	root.POST("/v1/exports/:id/cancel", h.cancel, rest.Secure(h.mw, "cancelExport")...)
	root.GET("/v1/exports/:id/download", h.download, rest.Secure(h.mw, "downloadExport")...)
}

func caller(req *http.Request) ucexport.Caller {
	ctx := req.Context()
	return ucexport.Caller{Subject: auth.SubjectFromContext(ctx), Manager: shared.HasPermission(ctx, "manageExports")}
}

func (h *RestHandler) create(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "ExportDeliveryREST:Create")
	defer trace.Finish()

	var payload domain.RequestCreateExport
	if !rest.DecodeBody(rw, req, h.validator, "export/create", &payload) {
		return
	}
	if code := ucexport.ExportPermission(payload.Type); !shared.HasPermission(ctx, code) {
		rest.WriteError(rw, rest.NewForbidden("missing permission "+code))
		return
	}
	result, err := h.uc.Export().RequestExport(ctx, caller(req), &payload)
	if err != nil {
		rest.WriteError(rw, err)
		return
	}
	wrapper.NewHTTPResponse(http.StatusAccepted, "Export queued", result).JSON(rw)
}

func (h *RestHandler) getAll(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "ExportDeliveryREST:GetAll")
	defer trace.Finish()

	var filter domain.FilterExport
	if !rest.ParseFilter(rw, req, h.validator, "export/get_all", &filter) {
		return
	}
	result, err := h.uc.Export().GetAllExports(ctx, caller(req), &filter)
	if err != nil {
		rest.WriteError(rw, err)
		return
	}
	response := wrapper.NewHTTPResponse(http.StatusOK, "Success", result.Data)
	response.Meta = result.Meta
	response.JSON(rw)
}

func (h *RestHandler) get(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "ExportDeliveryREST:Get")
	defer trace.Finish()

	result, err := h.uc.Export().GetExport(ctx, caller(req), restserver.URLParam(req, "id"))
	if err != nil {
		rest.WriteError(rw, err)
		return
	}
	rest.WriteOK(rw, result)
}

func (h *RestHandler) cancel(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "ExportDeliveryREST:Cancel")
	defer trace.Finish()

	result, err := h.uc.Export().CancelExport(ctx, caller(req), restserver.URLParam(req, "id"))
	if err != nil {
		rest.WriteError(rw, err)
		return
	}
	rest.WriteOK(rw, result)
}

func (h *RestHandler) download(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "ExportDeliveryREST:Download")
	defer trace.Finish()

	job, file, size, err := h.uc.Export().DownloadExport(ctx, caller(req), restserver.URLParam(req, "id"))
	if err != nil {
		rest.WriteError(rw, err)
		return
	}
	defer file.Close()
	rw.Header().Set("Content-Type", "text/csv; charset=utf-8")
	rw.Header().Set("Content-Disposition", `attachment; filename="`+job.FileName+`"`)
	rw.Header().Set("Content-Length", strconv.FormatInt(size, 10))
	rw.WriteHeader(http.StatusOK)
	_, _ = io.Copy(rw, file)
}
