// Code generated by candi v1.20.0.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	gatewayusecase "monorepo/services/payment/internal/modules/gateway/usecase"
	methodusecase "monorepo/services/payment/internal/modules/method/usecase"
	paymentusecase "monorepo/services/payment/internal/modules/payment/usecase"
	topicusecase "monorepo/services/payment/internal/modules/topic/usecase"
	"monorepo/services/payment/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		Payment() paymentusecase.PaymentUsecase
		Topic() topicusecase.TopicUsecase
		Method() methodusecase.MethodUsecase
		Gateway() gatewayusecase.GatewayUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		paymentusecase.PaymentUsecase
		topicusecase.TopicUsecase
		methodusecase.MethodUsecase
		gatewayusecase.GatewayUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.PaymentUsecase, setSharedUsecaseFunc = paymentusecase.NewPaymentUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.TopicUsecase, setSharedUsecaseFunc = topicusecase.NewTopicUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.MethodUsecase, setSharedUsecaseFunc = methodusecase.NewMethodUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.GatewayUsecase, setSharedUsecaseFunc = gatewayusecase.NewGatewayUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) Payment() paymentusecase.PaymentUsecase {
	return uc.PaymentUsecase
}

func (uc *usecaseUow) Topic() topicusecase.TopicUsecase {
	return uc.TopicUsecase
}

func (uc *usecaseUow) Method() methodusecase.MethodUsecase {
	return uc.MethodUsecase
}

func (uc *usecaseUow) Gateway() gatewayusecase.GatewayUsecase {
	return uc.GatewayUsecase
}
