// Code generated by candi v1.20.0.

package resthandler

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"

	"monorepo/services/notification/internal/modules/otp/domain"
	"monorepo/services/notification/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
func (h *RestHandler) Mount(root interfaces.RESTRouter) {
	v1Otp := root.Group(candihelper.V1+"/otp", h.mw.HTTPBearerAuth)

	v1Otp.POST("/request", h.requestOTP, h.mw.HTTPPermissionACL("requestOTP"))
	v1Otp.POST("/verify", h.verifyOTP, h.mw.HTTPPermissionACL("verifyOTP"))
}

// requestOTP godoc
// @Summary			Request OTP
// @Description		Generates a code, stores it hashed, and delivers it via email or push
// @Tags			OTP
// @Accept			json
// @Produce			json
// @Param			data	body	domain.RequestOTP	true	"Body Data"
// @Success			202	{object}	domain.ResponseRequestOTP
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/otp/request [post]
func (h *RestHandler) requestOTP(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "OtpDeliveryREST:RequestOTP")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("otp/save", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	var payload domain.RequestOTP
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	jobID, err := h.uc.Otp().RequestOTP(ctx, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusAccepted, "ok", domain.ResponseRequestOTP{JobID: jobID}).JSON(rw)
}

// verifyOTP godoc
// @Summary			Verify OTP
// @Tags			OTP
// @Accept			json
// @Produce			json
// @Param			data	body	domain.RequestVerifyOTP	true	"Body Data"
// @Success			200	{object}	domain.ResponseVerifyOTP
// @Success			400	{object}	wrapper.HTTPResponse
// @Success			404	{object}	wrapper.HTTPResponse
// @Success			410	{object}	wrapper.HTTPResponse
// @Success			429	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/otp/verify [post]
func (h *RestHandler) verifyOTP(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "OtpDeliveryREST:VerifyOTP")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	var payload domain.RequestVerifyOTP
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	verified, err := h.uc.Otp().VerifyOTP(ctx, &payload)
	if err != nil {
		code := http.StatusBadRequest
		switch {
		case errors.Is(err, domain.ErrOTPNotFound):
			code = http.StatusNotFound
		case errors.Is(err, domain.ErrOTPExpired):
			code = http.StatusGone
		case errors.Is(err, domain.ErrOTPTooManyAttempts):
			code = http.StatusTooManyRequests
		case errors.Is(err, domain.ErrOTPMismatch):
			code = http.StatusBadRequest
		}
		wrapper.NewHTTPResponse(code, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Success", domain.ResponseVerifyOTP{Verified: verified}).JSON(rw)
}
