// Code generated by candi v1.20.0.

package resthandler

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"monorepo/services/notification/internal/modules/otp/domain"
	mockusecase "monorepo/services/notification/pkg/mocks/modules/otp/usecase"
	mocksharedusecase "monorepo/services/notification/pkg/mocks/shared/usecase"

	mockdeps "github.com/golangid/candi/mocks/codebase/factory/dependency"
	mockinterfaces "github.com/golangid/candi/mocks/codebase/interfaces"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

func TestNewRestHandler(t *testing.T) {
	mockMiddleware := &mockinterfaces.Middleware{}
	mockMiddleware.On("HTTPPermissionACL", mock.Anything).Return(func(http.Handler) http.Handler { return nil })
	mockValidator := &mockinterfaces.Validator{}

	mockDeps := &mockdeps.Dependency{}
	mockDeps.On("GetMiddleware").Return(mockMiddleware)
	mockDeps.On("GetValidator").Return(mockValidator)

	handler := NewRestHandler(nil, mockDeps)
	assert.NotNil(t, handler)

	mockRoute := &mockinterfaces.RESTRouter{}
	mockRoute.On("Group", mock.Anything, mock.Anything).Return(mockRoute)
	mockRoute.On("POST", mock.Anything, mock.Anything, mock.Anything)
	handler.Mount(mockRoute)
}

func TestRestHandler_requestOTP(t *testing.T) {
	otpUsecase := &mockusecase.OtpUsecase{}
	otpUsecase.On("RequestOTP", mock.Anything, mock.Anything).Return("job-id", nil)
	uc := &mocksharedusecase.Usecase{}
	uc.On("Otp").Return(otpUsecase)

	mockValidator := &mockinterfaces.Validator{}
	mockValidator.On("ValidateDocument", mock.Anything, mock.Anything).Return(nil)

	handler := RestHandler{uc: uc, validator: mockValidator}
	req := httptest.NewRequest(http.MethodPost, "/", strings.NewReader(`{"recipient":"a@b.com","channel":"email","purpose":"login"}`))
	res := httptest.NewRecorder()
	handler.requestOTP(res, req)
	assert.Equal(t, http.StatusAccepted, res.Code)
}

func TestRestHandler_verifyOTP(t *testing.T) {
	tests := []struct {
		name         string
		ucErr        error
		wantRespCode int
	}{
		{name: "Positive", wantRespCode: http.StatusOK},
		{name: "Not found", ucErr: domain.ErrOTPNotFound, wantRespCode: http.StatusNotFound},
		{name: "Expired", ucErr: domain.ErrOTPExpired, wantRespCode: http.StatusGone},
		{name: "Too many attempts", ucErr: domain.ErrOTPTooManyAttempts, wantRespCode: http.StatusTooManyRequests},
		{name: "Mismatch", ucErr: domain.ErrOTPMismatch, wantRespCode: http.StatusBadRequest},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			otpUsecase := &mockusecase.OtpUsecase{}
			otpUsecase.On("VerifyOTP", mock.Anything, mock.Anything).Return(tt.ucErr == nil, tt.ucErr)
			uc := &mocksharedusecase.Usecase{}
			uc.On("Otp").Return(otpUsecase)

			handler := RestHandler{uc: uc}
			req := httptest.NewRequest(http.MethodPost, "/", strings.NewReader(`{"recipient":"a@b.com","purpose":"login","code":"123456"}`))
			res := httptest.NewRecorder()
			handler.verifyOTP(res, req)
			assert.Equal(t, tt.wantRespCode, res.Code)
		})
	}
}
