// Code generated by candi v1.20.0.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	authusecase "monorepo/services/user/internal/modules/auth/usecase"
	clientusecase "monorepo/services/user/internal/modules/client/usecase"
	menuusecase "monorepo/services/user/internal/modules/menu/usecase"
	rbacusecase "monorepo/services/user/internal/modules/rbac/usecase"
	realmusecase "monorepo/services/user/internal/modules/realm/usecase"
	userusecase "monorepo/services/user/internal/modules/user/usecase"
	"monorepo/services/user/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		User() userusecase.UserUsecase
		Realm() realmusecase.RealmUsecase
		Rbac() rbacusecase.RbacUsecase
		Menu() menuusecase.MenuUsecase
		Client() clientusecase.ClientUsecase
		Auth() authusecase.AuthUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		userusecase.UserUsecase
		realmusecase.RealmUsecase
		rbacusecase.RbacUsecase
		menuusecase.MenuUsecase
		clientusecase.ClientUsecase
		authusecase.AuthUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.UserUsecase, setSharedUsecaseFunc = userusecase.NewUserUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.RealmUsecase, setSharedUsecaseFunc = realmusecase.NewRealmUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.RbacUsecase, setSharedUsecaseFunc = rbacusecase.NewRbacUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.MenuUsecase, setSharedUsecaseFunc = menuusecase.NewMenuUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.ClientUsecase, setSharedUsecaseFunc = clientusecase.NewClientUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.AuthUsecase, setSharedUsecaseFunc = authusecase.NewAuthUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) User() userusecase.UserUsecase {
	return uc.UserUsecase
}

func (uc *usecaseUow) Realm() realmusecase.RealmUsecase {
	return uc.RealmUsecase
}

func (uc *usecaseUow) Rbac() rbacusecase.RbacUsecase {
	return uc.RbacUsecase
}

func (uc *usecaseUow) Menu() menuusecase.MenuUsecase {
	return uc.MenuUsecase
}

func (uc *usecaseUow) Client() clientusecase.ClientUsecase {
	return uc.ClientUsecase
}

func (uc *usecaseUow) Auth() authusecase.AuthUsecase {
	return uc.AuthUsecase
}
