// Code generated by candi v1.20.0.

package user

import (
	"context"

	"monorepo/services/user/internal/modules/auth"
	"monorepo/services/user/internal/modules/client"
	"monorepo/services/user/internal/modules/menu"
	"monorepo/services/user/internal/modules/rbac"
	"monorepo/services/user/internal/modules/realm"
	"monorepo/services/user/internal/modules/user"

	"monorepo/services/user/configs"
	"monorepo/services/user/internal/bootstrap"

	"github.com/golangid/candi/codebase/factory"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/factory/types"
	"github.com/golangid/candi/config"
)

// Service model
type Service struct {
	cfg          *config.Config
	deps         dependency.Dependency
	applications []factory.AppServerFactory
	modules      []factory.ModuleFactory
	name         types.Service
}

// NewService in this service
func NewService(cfg *config.Config) factory.ServiceFactory {
	deps := configs.LoadServiceConfigs(cfg)

	// seed the master realm, superadmin role / user and admin client before serving anything
	if err := bootstrap.Run(context.Background()); err != nil {
		panic("bootstrap failed (were the migrations applied? `make migration service=user`): " + err.Error())
	}

	modules := []factory.ModuleFactory{
		auth.NewModule(deps),
		client.NewModule(deps),
		menu.NewModule(deps),
		rbac.NewModule(deps),
		realm.NewModule(deps),
		user.NewModule(deps),
	}

	s := &Service{
		cfg:     cfg,
		deps:    deps,
		modules: modules,
		name:    types.Service(cfg.ServiceName),
	}

	s.applications = configs.InitAppFromEnvironmentConfig(s)

	// Add custom application runner, must implement `factory.AppServerFactory` methods
	s.applications = append(s.applications, []factory.AppServerFactory{
		// customApplication
	}...)

	return s
}

// GetConfig method
func (s *Service) GetConfig() *config.Config {
	return s.cfg
}

// GetDependency method
func (s *Service) GetDependency() dependency.Dependency {
	return s.deps
}

// GetApplications method
func (s *Service) GetApplications() []factory.AppServerFactory {
	return s.applications
}

// GetModules method
func (s *Service) GetModules() []factory.ModuleFactory {
	return s.modules
}

// Name method
func (s *Service) Name() types.Service {
	return s.name
}
