// Code generated by candi v1.20.0.

package usecase

import (
	"context"

	"monorepo/services/activity/internal/modules/activity/domain"
	"monorepo/services/activity/pkg/shared/repository"
	"monorepo/services/activity/pkg/shared/usecase/common"

	taskqueueworker "github.com/golangid/candi/codebase/app/task_queue_worker"
	"github.com/golangid/candi/codebase/factory/dependency"
)

// ActivityUsecase abstraction
type ActivityUsecase interface {
	// SaveActivityLog enqueues an activity log entry for async persistence and
	// returns immediately (REST-facing).
	SaveActivityLog(ctx context.Context, req *domain.RequestSaveActivity) (jobID string, err error)
	// PersistActivityLog does the actual Mongo write. Called only from the
	// task queue worker handler, never directly from REST.
	PersistActivityLog(ctx context.Context, req *domain.RequestSaveActivity) (err error)
	GetAllActivityLogs(ctx context.Context, filter *domain.FilterActivity) (data domain.ResponseActivityList, err error)
	GetActivityLogByID(ctx context.Context, id string) (data domain.ResponseActivity, err error)
}

type activityUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoMongo     repository.RepoMongo

	// jobEnqueuer wraps taskqueueworker.AddJob so it can be swapped out in tests.
	jobEnqueuer func(ctx context.Context, req *taskqueueworker.AddJobRequest) (string, error)
}

// NewActivityUsecase usecase impl constructor
func NewActivityUsecase(deps dependency.Dependency) (ActivityUsecase, func(sharedUsecase common.Usecase)) {
	uc := &activityUsecaseImpl{
		deps:        deps,
		repoMongo:   repository.GetSharedRepoMongo(),
		jobEnqueuer: taskqueueworker.AddJob,
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
