// Code generated by candi v1.20.0.

package repository

import (
	"context"
	"database/sql"
	"fmt"

	// @candi:repositoryImport
	authrepo "monorepo/services/user/internal/modules/auth/repository"
	clientrepo "monorepo/services/user/internal/modules/client/repository"
	menurepo "monorepo/services/user/internal/modules/menu/repository"
	rbacrepo "monorepo/services/user/internal/modules/rbac/repository"
	realmrepo "monorepo/services/user/internal/modules/realm/repository"
	userrepo "monorepo/services/user/internal/modules/user/repository"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"monorepo/globalshared"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

type (
	// RepoSQL abstraction
	RepoSQL interface {
		WithTransaction(ctx context.Context, txFunc func(ctx context.Context) error) (err error)

		// @candi:repositoryMethod
		UserRepo() userrepo.UserRepository
		RealmRepo() realmrepo.RealmRepository
		RealmKeyRepo() realmrepo.RealmKeyRepository
		RoleRepo() rbacrepo.RoleRepository
		PermissionRepo() rbacrepo.PermissionRepository
		MenuRepo() menurepo.MenuRepository
		ClientRepo() clientrepo.ClientRepository
		SessionRepo() authrepo.SessionRepository
	}

	repoSQLImpl struct {
		readDB, writeDB *gorm.DB

		// register all repository from modules
		// @candi:repositoryField
		userRepo       userrepo.UserRepository
		realmRepo      realmrepo.RealmRepository
		realmKeyRepo   realmrepo.RealmKeyRepository
		roleRepo       rbacrepo.RoleRepository
		permissionRepo rbacrepo.PermissionRepository
		menuRepo       menurepo.MenuRepository
		clientRepo     clientrepo.ClientRepository
		sessionRepo    authrepo.SessionRepository
	}
)

var (
	globalRepoSQL RepoSQL
)

// setSharedRepoSQL set the global singleton "RepoSQL" implementation
func setSharedRepoSQL(readDB, writeDB *sql.DB) {
	gormRead, err := gorm.Open(postgres.New(postgres.Config{
		Conn: readDB,
	}), &gorm.Config{})
	if err != nil {
		panic(err)
	}

	gormWrite, err := gorm.Open(postgres.New(postgres.Config{
		Conn: writeDB,
	}), &gorm.Config{SkipDefaultTransaction: true})
	if err != nil {
		panic(err)
	}

	globalshared.AddGormCallbacks(gormRead)
	globalshared.AddGormCallbacks(gormWrite)

	globalRepoSQL = NewRepositorySQL(gormRead, gormWrite)
}

// GetSharedRepoSQL returns the global singleton "RepoSQL" implementation
func GetSharedRepoSQL() RepoSQL {
	return globalRepoSQL
}

// NewRepositorySQL constructor
func NewRepositorySQL(readDB, writeDB *gorm.DB) RepoSQL {

	return &repoSQLImpl{
		readDB: readDB, writeDB: writeDB,

		// @candi:repositoryConstructor
		userRepo:       userrepo.NewUserRepoSQL(readDB, writeDB),
		realmRepo:      realmrepo.NewRealmRepoSQL(readDB, writeDB),
		realmKeyRepo:   realmrepo.NewRealmKeyRepoSQL(readDB, writeDB),
		roleRepo:       rbacrepo.NewRoleRepoSQL(readDB, writeDB),
		permissionRepo: rbacrepo.NewPermissionRepoSQL(readDB, writeDB),
		menuRepo:       menurepo.NewMenuRepoSQL(readDB, writeDB),
		clientRepo:     clientrepo.NewClientRepoSQL(readDB, writeDB),
		sessionRepo:    authrepo.NewSessionRepoSQL(readDB, writeDB),
	}
}

// WithTransaction run transaction for each repository with context, include handle canceled or timeout context
func (r *repoSQLImpl) WithTransaction(ctx context.Context, txFunc func(ctx context.Context) error) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "RepoSQL:Transaction")
	defer trace.Finish()

	tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB)
	if !ok {
		tx = r.writeDB.Begin()
		if tx.Error != nil {
			return tx.Error
		}

		defer func() {
			if err != nil {
				tx.Rollback()
				trace.SetError(err)
			} else {
				tx.Commit()
			}
		}()
		ctx = candishared.SetToContext(ctx, candishared.ContextKeySQLTransaction, tx)
	}

	errChan := make(chan error)
	go func(ctx context.Context) {
		defer func() {
			if r := recover(); r != nil {
				errChan <- fmt.Errorf("panic: %v", r)
			}
			close(errChan)
		}()

		if err := txFunc(ctx); err != nil {
			errChan <- err
		}
	}(ctx)

	select {
	case <-ctx.Done():
		return fmt.Errorf("Canceled or timeout: %v", ctx.Err())
	case e := <-errChan:
		return e
	}
}

// @candi:repositoryImplementation
func (r *repoSQLImpl) UserRepo() userrepo.UserRepository {
	return r.userRepo
}

func (r *repoSQLImpl) RealmRepo() realmrepo.RealmRepository {
	return r.realmRepo
}

func (r *repoSQLImpl) RealmKeyRepo() realmrepo.RealmKeyRepository {
	return r.realmKeyRepo
}

func (r *repoSQLImpl) RoleRepo() rbacrepo.RoleRepository {
	return r.roleRepo
}

func (r *repoSQLImpl) PermissionRepo() rbacrepo.PermissionRepository {
	return r.permissionRepo
}

func (r *repoSQLImpl) MenuRepo() menurepo.MenuRepository {
	return r.menuRepo
}

func (r *repoSQLImpl) ClientRepo() clientrepo.ClientRepository {
	return r.clientRepo
}

func (r *repoSQLImpl) SessionRepo() authrepo.SessionRepository {
	return r.sessionRepo
}
