package domain

import "time"

// ExportJob is an asynchronous CSV export: requested over REST, generated by the task queue worker,
// downloaded once completed. The table is the source of truth; the queue only carries the job id.
type ExportJob struct {
	ID              string     `gorm:"column:id;primary_key" json:"id"`
	Type            string     `gorm:"column:type" json:"type"`
	Filter          JSON       `gorm:"column:filter;type:jsonb" json:"filter"`
	Status          string     `gorm:"column:status" json:"status"`
	RequestedBy     string     `gorm:"column:requested_by" json:"requestedBy"`
	MerchantID      string     `gorm:"column:merchant_id" json:"merchantId"`
	TotalRows       int64      `gorm:"column:total_rows" json:"totalRows"`
	ProcessedRows   int64      `gorm:"column:processed_rows" json:"processedRows"`
	FileName        string     `gorm:"column:file_name" json:"fileName"`
	FileSize        int64      `gorm:"column:file_size" json:"fileSize"`
	Error           string     `gorm:"column:error" json:"error,omitempty"`
	Attempts        int        `gorm:"column:attempts" json:"attempts"`
	CancelRequested bool       `gorm:"column:cancel_requested" json:"cancelRequested"`
	HeartbeatAt     *time.Time `gorm:"column:heartbeat_at" json:"heartbeatAt"`
	StartedAt       *time.Time `gorm:"column:started_at" json:"startedAt"`
	FinishedAt      *time.Time `gorm:"column:finished_at" json:"finishedAt"`
	ExpiresAt       *time.Time `gorm:"column:expires_at" json:"expiresAt"`
	CreatedAt       time.Time  `gorm:"column:created_at" json:"createdAt"`
	UpdatedAt       time.Time  `gorm:"column:updated_at" json:"updatedAt"`
}

// TableName return table name of ExportJob model
func (ExportJob) TableName() string { return "export_jobs" }

// IsFinished reports whether the job can no longer run
func (j ExportJob) IsFinished() bool {
	switch j.Status {
	case ExportCompleted, ExportFailed, ExportCancelled, ExportExpired:
		return true
	}
	return false
}
