// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: shipment/shipment.proto

package shipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,3,opt,name=totalRecords,proto3" json:"totalRecords,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_shipment_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_shipment_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Meta) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Meta) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *Meta) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetAllShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	ShowAll       bool                   `protobuf:"varint,6,opt,name=showAll,proto3" json:"showAll,omitempty"`
	StartDate     string                 `protobuf:"bytes,7,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,8,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllShipmentRequest) Reset() {
	*x = GetAllShipmentRequest{}
	mi := &file_shipment_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllShipmentRequest) ProtoMessage() {}

func (x *GetAllShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetAllShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllShipmentRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllShipmentRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllShipmentRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllShipmentRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetAllShipmentRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetAllShipmentRequest) GetShowAll() bool {
	if x != nil {
		return x.ShowAll
	}
	return false
}

func (x *GetAllShipmentRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetAllShipmentRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetAllShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []*ShipmentModel       `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllShipmentResponse) Reset() {
	*x = GetAllShipmentResponse{}
	mi := &file_shipment_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllShipmentResponse) ProtoMessage() {}

func (x *GetAllShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetAllShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllShipmentResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetAllShipmentResponse) GetData() []*ShipmentModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDetailShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailShipmentRequest) Reset() {
	*x = GetDetailShipmentRequest{}
	mi := &file_shipment_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailShipmentRequest) ProtoMessage() {}

func (x *GetDetailShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetDetailShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *GetDetailShipmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestShipmentModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestShipmentModel) Reset() {
	*x = RequestShipmentModel{}
	mi := &file_shipment_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestShipmentModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestShipmentModel) ProtoMessage() {}

func (x *RequestShipmentModel) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestShipmentModel.ProtoReflect.Descriptor instead.
func (*RequestShipmentModel) Descriptor() ([]byte, []int) {
	return file_shipment_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *RequestShipmentModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestShipmentModel) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type ShipmentModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentModel) Reset() {
	*x = ShipmentModel{}
	mi := &file_shipment_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentModel) ProtoMessage() {}

func (x *ShipmentModel) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentModel.ProtoReflect.Descriptor instead.
func (*ShipmentModel) Descriptor() ([]byte, []int) {
	return file_shipment_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *ShipmentModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShipmentModel) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ShipmentModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ShipmentModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_shipment_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_shipment_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shipment_shipment_proto protoreflect.FileDescriptor

const file_shipment_shipment_proto_rawDesc = "" +
	"\n" +
	"\x17shipment/shipment.proto\x12\bshipment\"t\n" +
	"\x04Meta\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\"\n" +
	"\ftotalRecords\x18\x03 \x01(\x03R\ftotalRecords\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x04 \x01(\x03R\n" +
	"totalPages\"\xd9\x01\n" +
	"\x15GetAllShipmentRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x18\n" +
	"\aorderBy\x18\x04 \x01(\tR\aorderBy\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x18\n" +
	"\ashowAll\x18\x06 \x01(\bR\ashowAll\x12\x1c\n" +
	"\tstartDate\x18\a \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\b \x01(\tR\aendDate\"i\n" +
	"\x16GetAllShipmentResponse\x12\"\n" +
	"\x04meta\x18\x01 \x01(\v2\x0e.shipment.MetaR\x04meta\x12+\n" +
	"\x04data\x18\x02 \x03(\v2\x17.shipment.ShipmentModelR\x04data\"*\n" +
	"\x18GetDetailShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\x14RequestShipmentModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"q\n" +
	"\rShipmentModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAt\"(\n" +
	"\fBaseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x97\x03\n" +
	"\x0fShipmentHandler\x12S\n" +
	"\x0eGetAllShipment\x12\x1f.shipment.GetAllShipmentRequest\x1a .shipment.GetAllShipmentResponse\x12P\n" +
	"\x11GetDetailShipment\x12\".shipment.GetDetailShipmentRequest\x1a\x17.shipment.ShipmentModel\x12I\n" +
	"\x0eCreateShipment\x12\x1e.shipment.RequestShipmentModel\x1a\x17.shipment.ShipmentModel\x12H\n" +
	"\x0eUpdateShipment\x12\x1e.shipment.RequestShipmentModel\x1a\x16.shipment.BaseResponse\x12H\n" +
	"\x0eDeleteShipment\x12\x1e.shipment.RequestShipmentModel\x1a\x16.shipment.BaseResponseB/Z-monorepo/services/shipment/api/proto/shipmentb\x06proto3"

var (
	file_shipment_shipment_proto_rawDescOnce sync.Once
	file_shipment_shipment_proto_rawDescData []byte
)

func file_shipment_shipment_proto_rawDescGZIP() []byte {
	file_shipment_shipment_proto_rawDescOnce.Do(func() {
		file_shipment_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipment_shipment_proto_rawDesc), len(file_shipment_shipment_proto_rawDesc)))
	})
	return file_shipment_shipment_proto_rawDescData
}

var file_shipment_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shipment_shipment_proto_goTypes = []any{
	(*Meta)(nil),                     // 0: shipment.Meta
	(*GetAllShipmentRequest)(nil),    // 1: shipment.GetAllShipmentRequest
	(*GetAllShipmentResponse)(nil),   // 2: shipment.GetAllShipmentResponse
	(*GetDetailShipmentRequest)(nil), // 3: shipment.GetDetailShipmentRequest
	(*RequestShipmentModel)(nil),     // 4: shipment.RequestShipmentModel
	(*ShipmentModel)(nil),            // 5: shipment.ShipmentModel
	(*BaseResponse)(nil),             // 6: shipment.BaseResponse
}
var file_shipment_shipment_proto_depIdxs = []int32{
	0, // 0: shipment.GetAllShipmentResponse.meta:type_name -> shipment.Meta
	5, // 1: shipment.GetAllShipmentResponse.data:type_name -> shipment.ShipmentModel
	1, // 2: shipment.ShipmentHandler.GetAllShipment:input_type -> shipment.GetAllShipmentRequest
	3, // 3: shipment.ShipmentHandler.GetDetailShipment:input_type -> shipment.GetDetailShipmentRequest
	4, // 4: shipment.ShipmentHandler.CreateShipment:input_type -> shipment.RequestShipmentModel
	4, // 5: shipment.ShipmentHandler.UpdateShipment:input_type -> shipment.RequestShipmentModel
	4, // 6: shipment.ShipmentHandler.DeleteShipment:input_type -> shipment.RequestShipmentModel
	2, // 7: shipment.ShipmentHandler.GetAllShipment:output_type -> shipment.GetAllShipmentResponse
	5, // 8: shipment.ShipmentHandler.GetDetailShipment:output_type -> shipment.ShipmentModel
	5, // 9: shipment.ShipmentHandler.CreateShipment:output_type -> shipment.ShipmentModel
	6, // 10: shipment.ShipmentHandler.UpdateShipment:output_type -> shipment.BaseResponse
	6, // 11: shipment.ShipmentHandler.DeleteShipment:output_type -> shipment.BaseResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shipment_shipment_proto_init() }
func file_shipment_shipment_proto_init() {
	if File_shipment_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipment_shipment_proto_rawDesc), len(file_shipment_shipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipment_shipment_proto_goTypes,
		DependencyIndexes: file_shipment_shipment_proto_depIdxs,
		MessageInfos:      file_shipment_shipment_proto_msgTypes,
	}.Build()
	File_shipment_shipment_proto = out.File
	file_shipment_shipment_proto_goTypes = nil
	file_shipment_shipment_proto_depIdxs = nil
}
