// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: shipment/shipment.proto

package shipment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShipmentHandler_GetAllShipment_FullMethodName    = "/shipment.ShipmentHandler/GetAllShipment"
	ShipmentHandler_GetDetailShipment_FullMethodName = "/shipment.ShipmentHandler/GetDetailShipment"
	ShipmentHandler_CreateShipment_FullMethodName    = "/shipment.ShipmentHandler/CreateShipment"
	ShipmentHandler_UpdateShipment_FullMethodName    = "/shipment.ShipmentHandler/UpdateShipment"
	ShipmentHandler_DeleteShipment_FullMethodName    = "/shipment.ShipmentHandler/DeleteShipment"
)

// ShipmentHandlerClient is the client API for ShipmentHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShipmentHandlerClient interface {
	GetAllShipment(ctx context.Context, in *GetAllShipmentRequest, opts ...grpc.CallOption) (*GetAllShipmentResponse, error)
	GetDetailShipment(ctx context.Context, in *GetDetailShipmentRequest, opts ...grpc.CallOption) (*ShipmentModel, error)
	CreateShipment(ctx context.Context, in *RequestShipmentModel, opts ...grpc.CallOption) (*ShipmentModel, error)
	UpdateShipment(ctx context.Context, in *RequestShipmentModel, opts ...grpc.CallOption) (*BaseResponse, error)
	DeleteShipment(ctx context.Context, in *RequestShipmentModel, opts ...grpc.CallOption) (*BaseResponse, error)
}

type shipmentHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewShipmentHandlerClient(cc grpc.ClientConnInterface) ShipmentHandlerClient {
	return &shipmentHandlerClient{cc}
}

func (c *shipmentHandlerClient) GetAllShipment(ctx context.Context, in *GetAllShipmentRequest, opts ...grpc.CallOption) (*GetAllShipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllShipmentResponse)
	err := c.cc.Invoke(ctx, ShipmentHandler_GetAllShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentHandlerClient) GetDetailShipment(ctx context.Context, in *GetDetailShipmentRequest, opts ...grpc.CallOption) (*ShipmentModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipmentModel)
	err := c.cc.Invoke(ctx, ShipmentHandler_GetDetailShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentHandlerClient) CreateShipment(ctx context.Context, in *RequestShipmentModel, opts ...grpc.CallOption) (*ShipmentModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipmentModel)
	err := c.cc.Invoke(ctx, ShipmentHandler_CreateShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentHandlerClient) UpdateShipment(ctx context.Context, in *RequestShipmentModel, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, ShipmentHandler_UpdateShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentHandlerClient) DeleteShipment(ctx context.Context, in *RequestShipmentModel, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, ShipmentHandler_DeleteShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShipmentHandlerServer is the server API for ShipmentHandler service.
// All implementations should embed UnimplementedShipmentHandlerServer
// for forward compatibility.
type ShipmentHandlerServer interface {
	GetAllShipment(context.Context, *GetAllShipmentRequest) (*GetAllShipmentResponse, error)
	GetDetailShipment(context.Context, *GetDetailShipmentRequest) (*ShipmentModel, error)
	CreateShipment(context.Context, *RequestShipmentModel) (*ShipmentModel, error)
	UpdateShipment(context.Context, *RequestShipmentModel) (*BaseResponse, error)
	DeleteShipment(context.Context, *RequestShipmentModel) (*BaseResponse, error)
}

// UnimplementedShipmentHandlerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShipmentHandlerServer struct{}

func (UnimplementedShipmentHandlerServer) GetAllShipment(context.Context, *GetAllShipmentRequest) (*GetAllShipmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllShipment not implemented")
}
func (UnimplementedShipmentHandlerServer) GetDetailShipment(context.Context, *GetDetailShipmentRequest) (*ShipmentModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetailShipment not implemented")
}
func (UnimplementedShipmentHandlerServer) CreateShipment(context.Context, *RequestShipmentModel) (*ShipmentModel, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShipment not implemented")
}
func (UnimplementedShipmentHandlerServer) UpdateShipment(context.Context, *RequestShipmentModel) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShipment not implemented")
}
func (UnimplementedShipmentHandlerServer) DeleteShipment(context.Context, *RequestShipmentModel) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShipment not implemented")
}
func (UnimplementedShipmentHandlerServer) testEmbeddedByValue() {}

// UnsafeShipmentHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShipmentHandlerServer will
// result in compilation errors.
type UnsafeShipmentHandlerServer interface {
	mustEmbedUnimplementedShipmentHandlerServer()
}

func RegisterShipmentHandlerServer(s grpc.ServiceRegistrar, srv ShipmentHandlerServer) {
	// If the following call panics, it indicates UnimplementedShipmentHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShipmentHandler_ServiceDesc, srv)
}

func _ShipmentHandler_GetAllShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentHandlerServer).GetAllShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentHandler_GetAllShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentHandlerServer).GetAllShipment(ctx, req.(*GetAllShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentHandler_GetDetailShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentHandlerServer).GetDetailShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentHandler_GetDetailShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentHandlerServer).GetDetailShipment(ctx, req.(*GetDetailShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentHandler_CreateShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestShipmentModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentHandlerServer).CreateShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentHandler_CreateShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentHandlerServer).CreateShipment(ctx, req.(*RequestShipmentModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentHandler_UpdateShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestShipmentModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentHandlerServer).UpdateShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentHandler_UpdateShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentHandlerServer).UpdateShipment(ctx, req.(*RequestShipmentModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentHandler_DeleteShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestShipmentModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentHandlerServer).DeleteShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentHandler_DeleteShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentHandlerServer).DeleteShipment(ctx, req.(*RequestShipmentModel))
	}
	return interceptor(ctx, in, info, handler)
}

// ShipmentHandler_ServiceDesc is the grpc.ServiceDesc for ShipmentHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShipmentHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipment.ShipmentHandler",
	HandlerType: (*ShipmentHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllShipment",
			Handler:    _ShipmentHandler_GetAllShipment_Handler,
		},
		{
			MethodName: "GetDetailShipment",
			Handler:    _ShipmentHandler_GetDetailShipment_Handler,
		},
		{
			MethodName: "CreateShipment",
			Handler:    _ShipmentHandler_CreateShipment_Handler,
		},
		{
			MethodName: "UpdateShipment",
			Handler:    _ShipmentHandler_UpdateShipment_Handler,
		},
		{
			MethodName: "DeleteShipment",
			Handler:    _ShipmentHandler_DeleteShipment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipment/shipment.proto",
}
