// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: kitchen/kitchen.proto

package kitchen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KitchenHandler_GetAllKitchen_FullMethodName    = "/kitchen.KitchenHandler/GetAllKitchen"
	KitchenHandler_GetDetailKitchen_FullMethodName = "/kitchen.KitchenHandler/GetDetailKitchen"
	KitchenHandler_CreateKitchen_FullMethodName    = "/kitchen.KitchenHandler/CreateKitchen"
	KitchenHandler_UpdateKitchen_FullMethodName    = "/kitchen.KitchenHandler/UpdateKitchen"
	KitchenHandler_DeleteKitchen_FullMethodName    = "/kitchen.KitchenHandler/DeleteKitchen"
)

// KitchenHandlerClient is the client API for KitchenHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KitchenHandlerClient interface {
	GetAllKitchen(ctx context.Context, in *GetAllKitchenRequest, opts ...grpc.CallOption) (*GetAllKitchenResponse, error)
	GetDetailKitchen(ctx context.Context, in *GetDetailKitchenRequest, opts ...grpc.CallOption) (*KitchenModel, error)
	CreateKitchen(ctx context.Context, in *RequestKitchenModel, opts ...grpc.CallOption) (*KitchenModel, error)
	UpdateKitchen(ctx context.Context, in *RequestKitchenModel, opts ...grpc.CallOption) (*BaseResponse, error)
	DeleteKitchen(ctx context.Context, in *RequestKitchenModel, opts ...grpc.CallOption) (*BaseResponse, error)
}

type kitchenHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewKitchenHandlerClient(cc grpc.ClientConnInterface) KitchenHandlerClient {
	return &kitchenHandlerClient{cc}
}

func (c *kitchenHandlerClient) GetAllKitchen(ctx context.Context, in *GetAllKitchenRequest, opts ...grpc.CallOption) (*GetAllKitchenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllKitchenResponse)
	err := c.cc.Invoke(ctx, KitchenHandler_GetAllKitchen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenHandlerClient) GetDetailKitchen(ctx context.Context, in *GetDetailKitchenRequest, opts ...grpc.CallOption) (*KitchenModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KitchenModel)
	err := c.cc.Invoke(ctx, KitchenHandler_GetDetailKitchen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenHandlerClient) CreateKitchen(ctx context.Context, in *RequestKitchenModel, opts ...grpc.CallOption) (*KitchenModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KitchenModel)
	err := c.cc.Invoke(ctx, KitchenHandler_CreateKitchen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenHandlerClient) UpdateKitchen(ctx context.Context, in *RequestKitchenModel, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, KitchenHandler_UpdateKitchen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenHandlerClient) DeleteKitchen(ctx context.Context, in *RequestKitchenModel, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, KitchenHandler_DeleteKitchen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KitchenHandlerServer is the server API for KitchenHandler service.
// All implementations should embed UnimplementedKitchenHandlerServer
// for forward compatibility.
type KitchenHandlerServer interface {
	GetAllKitchen(context.Context, *GetAllKitchenRequest) (*GetAllKitchenResponse, error)
	GetDetailKitchen(context.Context, *GetDetailKitchenRequest) (*KitchenModel, error)
	CreateKitchen(context.Context, *RequestKitchenModel) (*KitchenModel, error)
	UpdateKitchen(context.Context, *RequestKitchenModel) (*BaseResponse, error)
	DeleteKitchen(context.Context, *RequestKitchenModel) (*BaseResponse, error)
}

// UnimplementedKitchenHandlerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKitchenHandlerServer struct{}

func (UnimplementedKitchenHandlerServer) GetAllKitchen(context.Context, *GetAllKitchenRequest) (*GetAllKitchenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllKitchen not implemented")
}
func (UnimplementedKitchenHandlerServer) GetDetailKitchen(context.Context, *GetDetailKitchenRequest) (*KitchenModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetailKitchen not implemented")
}
func (UnimplementedKitchenHandlerServer) CreateKitchen(context.Context, *RequestKitchenModel) (*KitchenModel, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKitchen not implemented")
}
func (UnimplementedKitchenHandlerServer) UpdateKitchen(context.Context, *RequestKitchenModel) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKitchen not implemented")
}
func (UnimplementedKitchenHandlerServer) DeleteKitchen(context.Context, *RequestKitchenModel) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKitchen not implemented")
}
func (UnimplementedKitchenHandlerServer) testEmbeddedByValue() {}

// UnsafeKitchenHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KitchenHandlerServer will
// result in compilation errors.
type UnsafeKitchenHandlerServer interface {
	mustEmbedUnimplementedKitchenHandlerServer()
}

func RegisterKitchenHandlerServer(s grpc.ServiceRegistrar, srv KitchenHandlerServer) {
	// If the following call panics, it indicates UnimplementedKitchenHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KitchenHandler_ServiceDesc, srv)
}

func _KitchenHandler_GetAllKitchen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllKitchenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenHandlerServer).GetAllKitchen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenHandler_GetAllKitchen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenHandlerServer).GetAllKitchen(ctx, req.(*GetAllKitchenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenHandler_GetDetailKitchen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailKitchenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenHandlerServer).GetDetailKitchen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenHandler_GetDetailKitchen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenHandlerServer).GetDetailKitchen(ctx, req.(*GetDetailKitchenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenHandler_CreateKitchen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestKitchenModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenHandlerServer).CreateKitchen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenHandler_CreateKitchen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenHandlerServer).CreateKitchen(ctx, req.(*RequestKitchenModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenHandler_UpdateKitchen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestKitchenModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenHandlerServer).UpdateKitchen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenHandler_UpdateKitchen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenHandlerServer).UpdateKitchen(ctx, req.(*RequestKitchenModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenHandler_DeleteKitchen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestKitchenModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenHandlerServer).DeleteKitchen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenHandler_DeleteKitchen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenHandlerServer).DeleteKitchen(ctx, req.(*RequestKitchenModel))
	}
	return interceptor(ctx, in, info, handler)
}

// KitchenHandler_ServiceDesc is the grpc.ServiceDesc for KitchenHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KitchenHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kitchen.KitchenHandler",
	HandlerType: (*KitchenHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllKitchen",
			Handler:    _KitchenHandler_GetAllKitchen_Handler,
		},
		{
			MethodName: "GetDetailKitchen",
			Handler:    _KitchenHandler_GetDetailKitchen_Handler,
		},
		{
			MethodName: "CreateKitchen",
			Handler:    _KitchenHandler_CreateKitchen_Handler,
		},
		{
			MethodName: "UpdateKitchen",
			Handler:    _KitchenHandler_UpdateKitchen_Handler,
		},
		{
			MethodName: "DeleteKitchen",
			Handler:    _KitchenHandler_DeleteKitchen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kitchen/kitchen.proto",
}
