// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: kitchen/kitchen.proto

package kitchen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,3,opt,name=totalRecords,proto3" json:"totalRecords,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_kitchen_kitchen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_kitchen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_kitchen_kitchen_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Meta) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Meta) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *Meta) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetAllKitchenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	ShowAll       bool                   `protobuf:"varint,6,opt,name=showAll,proto3" json:"showAll,omitempty"`
	StartDate     string                 `protobuf:"bytes,7,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,8,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllKitchenRequest) Reset() {
	*x = GetAllKitchenRequest{}
	mi := &file_kitchen_kitchen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllKitchenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllKitchenRequest) ProtoMessage() {}

func (x *GetAllKitchenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_kitchen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllKitchenRequest.ProtoReflect.Descriptor instead.
func (*GetAllKitchenRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_kitchen_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllKitchenRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllKitchenRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllKitchenRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllKitchenRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetAllKitchenRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetAllKitchenRequest) GetShowAll() bool {
	if x != nil {
		return x.ShowAll
	}
	return false
}

func (x *GetAllKitchenRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetAllKitchenRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetAllKitchenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []*KitchenModel        `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllKitchenResponse) Reset() {
	*x = GetAllKitchenResponse{}
	mi := &file_kitchen_kitchen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllKitchenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllKitchenResponse) ProtoMessage() {}

func (x *GetAllKitchenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_kitchen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllKitchenResponse.ProtoReflect.Descriptor instead.
func (*GetAllKitchenResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_kitchen_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllKitchenResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetAllKitchenResponse) GetData() []*KitchenModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDetailKitchenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailKitchenRequest) Reset() {
	*x = GetDetailKitchenRequest{}
	mi := &file_kitchen_kitchen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailKitchenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailKitchenRequest) ProtoMessage() {}

func (x *GetDetailKitchenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_kitchen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailKitchenRequest.ProtoReflect.Descriptor instead.
func (*GetDetailKitchenRequest) Descriptor() ([]byte, []int) {
	return file_kitchen_kitchen_proto_rawDescGZIP(), []int{3}
}

func (x *GetDetailKitchenRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestKitchenModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestKitchenModel) Reset() {
	*x = RequestKitchenModel{}
	mi := &file_kitchen_kitchen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestKitchenModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestKitchenModel) ProtoMessage() {}

func (x *RequestKitchenModel) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_kitchen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestKitchenModel.ProtoReflect.Descriptor instead.
func (*RequestKitchenModel) Descriptor() ([]byte, []int) {
	return file_kitchen_kitchen_proto_rawDescGZIP(), []int{4}
}

func (x *RequestKitchenModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestKitchenModel) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type KitchenModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KitchenModel) Reset() {
	*x = KitchenModel{}
	mi := &file_kitchen_kitchen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KitchenModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenModel) ProtoMessage() {}

func (x *KitchenModel) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_kitchen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenModel.ProtoReflect.Descriptor instead.
func (*KitchenModel) Descriptor() ([]byte, []int) {
	return file_kitchen_kitchen_proto_rawDescGZIP(), []int{5}
}

func (x *KitchenModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KitchenModel) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *KitchenModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *KitchenModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_kitchen_kitchen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kitchen_kitchen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_kitchen_kitchen_proto_rawDescGZIP(), []int{6}
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kitchen_kitchen_proto protoreflect.FileDescriptor

const file_kitchen_kitchen_proto_rawDesc = "" +
	"\n" +
	"\x15kitchen/kitchen.proto\x12\akitchen\"t\n" +
	"\x04Meta\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\"\n" +
	"\ftotalRecords\x18\x03 \x01(\x03R\ftotalRecords\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x04 \x01(\x03R\n" +
	"totalPages\"\xd8\x01\n" +
	"\x14GetAllKitchenRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x18\n" +
	"\aorderBy\x18\x04 \x01(\tR\aorderBy\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x18\n" +
	"\ashowAll\x18\x06 \x01(\bR\ashowAll\x12\x1c\n" +
	"\tstartDate\x18\a \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\b \x01(\tR\aendDate\"e\n" +
	"\x15GetAllKitchenResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.kitchen.MetaR\x04meta\x12)\n" +
	"\x04data\x18\x02 \x03(\v2\x15.kitchen.KitchenModelR\x04data\")\n" +
	"\x17GetDetailKitchenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x13RequestKitchenModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"p\n" +
	"\fKitchenModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAt\"(\n" +
	"\fBaseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xff\x02\n" +
	"\x0eKitchenHandler\x12N\n" +
	"\rGetAllKitchen\x12\x1d.kitchen.GetAllKitchenRequest\x1a\x1e.kitchen.GetAllKitchenResponse\x12K\n" +
	"\x10GetDetailKitchen\x12 .kitchen.GetDetailKitchenRequest\x1a\x15.kitchen.KitchenModel\x12D\n" +
	"\rCreateKitchen\x12\x1c.kitchen.RequestKitchenModel\x1a\x15.kitchen.KitchenModel\x12D\n" +
	"\rUpdateKitchen\x12\x1c.kitchen.RequestKitchenModel\x1a\x15.kitchen.BaseResponse\x12D\n" +
	"\rDeleteKitchen\x12\x1c.kitchen.RequestKitchenModel\x1a\x15.kitchen.BaseResponseB-Z+monorepo/services/kitchen/api/proto/kitchenb\x06proto3"

var (
	file_kitchen_kitchen_proto_rawDescOnce sync.Once
	file_kitchen_kitchen_proto_rawDescData []byte
)

func file_kitchen_kitchen_proto_rawDescGZIP() []byte {
	file_kitchen_kitchen_proto_rawDescOnce.Do(func() {
		file_kitchen_kitchen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kitchen_kitchen_proto_rawDesc), len(file_kitchen_kitchen_proto_rawDesc)))
	})
	return file_kitchen_kitchen_proto_rawDescData
}

var file_kitchen_kitchen_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kitchen_kitchen_proto_goTypes = []any{
	(*Meta)(nil),                    // 0: kitchen.Meta
	(*GetAllKitchenRequest)(nil),    // 1: kitchen.GetAllKitchenRequest
	(*GetAllKitchenResponse)(nil),   // 2: kitchen.GetAllKitchenResponse
	(*GetDetailKitchenRequest)(nil), // 3: kitchen.GetDetailKitchenRequest
	(*RequestKitchenModel)(nil),     // 4: kitchen.RequestKitchenModel
	(*KitchenModel)(nil),            // 5: kitchen.KitchenModel
	(*BaseResponse)(nil),            // 6: kitchen.BaseResponse
}
var file_kitchen_kitchen_proto_depIdxs = []int32{
	0, // 0: kitchen.GetAllKitchenResponse.meta:type_name -> kitchen.Meta
	5, // 1: kitchen.GetAllKitchenResponse.data:type_name -> kitchen.KitchenModel
	1, // 2: kitchen.KitchenHandler.GetAllKitchen:input_type -> kitchen.GetAllKitchenRequest
	3, // 3: kitchen.KitchenHandler.GetDetailKitchen:input_type -> kitchen.GetDetailKitchenRequest
	4, // 4: kitchen.KitchenHandler.CreateKitchen:input_type -> kitchen.RequestKitchenModel
	4, // 5: kitchen.KitchenHandler.UpdateKitchen:input_type -> kitchen.RequestKitchenModel
	4, // 6: kitchen.KitchenHandler.DeleteKitchen:input_type -> kitchen.RequestKitchenModel
	2, // 7: kitchen.KitchenHandler.GetAllKitchen:output_type -> kitchen.GetAllKitchenResponse
	5, // 8: kitchen.KitchenHandler.GetDetailKitchen:output_type -> kitchen.KitchenModel
	5, // 9: kitchen.KitchenHandler.CreateKitchen:output_type -> kitchen.KitchenModel
	6, // 10: kitchen.KitchenHandler.UpdateKitchen:output_type -> kitchen.BaseResponse
	6, // 11: kitchen.KitchenHandler.DeleteKitchen:output_type -> kitchen.BaseResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kitchen_kitchen_proto_init() }
func file_kitchen_kitchen_proto_init() {
	if File_kitchen_kitchen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kitchen_kitchen_proto_rawDesc), len(file_kitchen_kitchen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kitchen_kitchen_proto_goTypes,
		DependencyIndexes: file_kitchen_kitchen_proto_depIdxs,
		MessageInfos:      file_kitchen_kitchen_proto_msgTypes,
	}.Build()
	File_kitchen_kitchen_proto = out.File
	file_kitchen_kitchen_proto_goTypes = nil
	file_kitchen_kitchen_proto_depIdxs = nil
}
