// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,3,opt,name=totalRecords,proto3" json:"totalRecords,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Meta) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Meta) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *Meta) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetAllUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	ShowAll       bool                   `protobuf:"varint,6,opt,name=showAll,proto3" json:"showAll,omitempty"`
	StartDate     string                 `protobuf:"bytes,7,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,8,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserRequest) Reset() {
	*x = GetAllUserRequest{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserRequest) ProtoMessage() {}

func (x *GetAllUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserRequest.ProtoReflect.Descriptor instead.
func (*GetAllUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllUserRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllUserRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllUserRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllUserRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetAllUserRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetAllUserRequest) GetShowAll() bool {
	if x != nil {
		return x.ShowAll
	}
	return false
}

func (x *GetAllUserRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetAllUserRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetAllUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []*UserModel           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserResponse) Reset() {
	*x = GetAllUserResponse{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserResponse) ProtoMessage() {}

func (x *GetAllUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllUserResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetAllUserResponse) GetData() []*UserModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDetailUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailUserRequest) Reset() {
	*x = GetDetailUserRequest{}
	mi := &file_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailUserRequest) ProtoMessage() {}

func (x *GetDetailUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailUserRequest.ProtoReflect.Descriptor instead.
func (*GetDetailUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetDetailUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestUserModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUserModel) Reset() {
	*x = RequestUserModel{}
	mi := &file_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUserModel) ProtoMessage() {}

func (x *RequestUserModel) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUserModel.ProtoReflect.Descriptor instead.
func (*RequestUserModel) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *RequestUserModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestUserModel) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type UserModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserModel) Reset() {
	*x = UserModel{}
	mi := &file_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel) ProtoMessage() {}

func (x *UserModel) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel.ProtoReflect.Descriptor instead.
func (*UserModel) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserModel) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *UserModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\"t\n" +
	"\x04Meta\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\"\n" +
	"\ftotalRecords\x18\x03 \x01(\x03R\ftotalRecords\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x04 \x01(\x03R\n" +
	"totalPages\"\xd5\x01\n" +
	"\x11GetAllUserRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x18\n" +
	"\aorderBy\x18\x04 \x01(\tR\aorderBy\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x18\n" +
	"\ashowAll\x18\x06 \x01(\bR\ashowAll\x12\x1c\n" +
	"\tstartDate\x18\a \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\b \x01(\tR\aendDate\"Y\n" +
	"\x12GetAllUserResponse\x12\x1e\n" +
	"\x04meta\x18\x01 \x01(\v2\n" +
	".user.MetaR\x04meta\x12#\n" +
	"\x04data\x18\x02 \x03(\v2\x0f.user.UserModelR\x04data\"&\n" +
	"\x14GetDetailUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x10RequestUserModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"m\n" +
	"\tUserModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAt\"(\n" +
	"\fBaseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb7\x02\n" +
	"\vUserHandler\x12?\n" +
	"\n" +
	"GetAllUser\x12\x17.user.GetAllUserRequest\x1a\x18.user.GetAllUserResponse\x12<\n" +
	"\rGetDetailUser\x12\x1a.user.GetDetailUserRequest\x1a\x0f.user.UserModel\x125\n" +
	"\n" +
	"CreateUser\x12\x16.user.RequestUserModel\x1a\x0f.user.UserModel\x128\n" +
	"\n" +
	"UpdateUser\x12\x16.user.RequestUserModel\x1a\x12.user.BaseResponse\x128\n" +
	"\n" +
	"DeleteUser\x12\x16.user.RequestUserModel\x1a\x12.user.BaseResponseB'Z%monorepo/services/user/api/proto/userb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_user_user_proto_goTypes = []any{
	(*Meta)(nil),                 // 0: user.Meta
	(*GetAllUserRequest)(nil),    // 1: user.GetAllUserRequest
	(*GetAllUserResponse)(nil),   // 2: user.GetAllUserResponse
	(*GetDetailUserRequest)(nil), // 3: user.GetDetailUserRequest
	(*RequestUserModel)(nil),     // 4: user.RequestUserModel
	(*UserModel)(nil),            // 5: user.UserModel
	(*BaseResponse)(nil),         // 6: user.BaseResponse
}
var file_user_user_proto_depIdxs = []int32{
	0, // 0: user.GetAllUserResponse.meta:type_name -> user.Meta
	5, // 1: user.GetAllUserResponse.data:type_name -> user.UserModel
	1, // 2: user.UserHandler.GetAllUser:input_type -> user.GetAllUserRequest
	3, // 3: user.UserHandler.GetDetailUser:input_type -> user.GetDetailUserRequest
	4, // 4: user.UserHandler.CreateUser:input_type -> user.RequestUserModel
	4, // 5: user.UserHandler.UpdateUser:input_type -> user.RequestUserModel
	4, // 6: user.UserHandler.DeleteUser:input_type -> user.RequestUserModel
	2, // 7: user.UserHandler.GetAllUser:output_type -> user.GetAllUserResponse
	5, // 8: user.UserHandler.GetDetailUser:output_type -> user.UserModel
	5, // 9: user.UserHandler.CreateUser:output_type -> user.UserModel
	6, // 10: user.UserHandler.UpdateUser:output_type -> user.BaseResponse
	6, // 11: user.UserHandler.DeleteUser:output_type -> user.BaseResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
