// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserHandler_GetAllUser_FullMethodName    = "/user.UserHandler/GetAllUser"
	UserHandler_GetDetailUser_FullMethodName = "/user.UserHandler/GetDetailUser"
	UserHandler_CreateUser_FullMethodName    = "/user.UserHandler/CreateUser"
	UserHandler_UpdateUser_FullMethodName    = "/user.UserHandler/UpdateUser"
	UserHandler_DeleteUser_FullMethodName    = "/user.UserHandler/DeleteUser"
)

// UserHandlerClient is the client API for UserHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserHandlerClient interface {
	GetAllUser(ctx context.Context, in *GetAllUserRequest, opts ...grpc.CallOption) (*GetAllUserResponse, error)
	GetDetailUser(ctx context.Context, in *GetDetailUserRequest, opts ...grpc.CallOption) (*UserModel, error)
	CreateUser(ctx context.Context, in *RequestUserModel, opts ...grpc.CallOption) (*UserModel, error)
	UpdateUser(ctx context.Context, in *RequestUserModel, opts ...grpc.CallOption) (*BaseResponse, error)
	DeleteUser(ctx context.Context, in *RequestUserModel, opts ...grpc.CallOption) (*BaseResponse, error)
}

type userHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewUserHandlerClient(cc grpc.ClientConnInterface) UserHandlerClient {
	return &userHandlerClient{cc}
}

func (c *userHandlerClient) GetAllUser(ctx context.Context, in *GetAllUserRequest, opts ...grpc.CallOption) (*GetAllUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUserResponse)
	err := c.cc.Invoke(ctx, UserHandler_GetAllUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) GetDetailUser(ctx context.Context, in *GetDetailUserRequest, opts ...grpc.CallOption) (*UserModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserModel)
	err := c.cc.Invoke(ctx, UserHandler_GetDetailUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) CreateUser(ctx context.Context, in *RequestUserModel, opts ...grpc.CallOption) (*UserModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserModel)
	err := c.cc.Invoke(ctx, UserHandler_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) UpdateUser(ctx context.Context, in *RequestUserModel, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, UserHandler_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userHandlerClient) DeleteUser(ctx context.Context, in *RequestUserModel, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, UserHandler_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserHandlerServer is the server API for UserHandler service.
// All implementations should embed UnimplementedUserHandlerServer
// for forward compatibility.
type UserHandlerServer interface {
	GetAllUser(context.Context, *GetAllUserRequest) (*GetAllUserResponse, error)
	GetDetailUser(context.Context, *GetDetailUserRequest) (*UserModel, error)
	CreateUser(context.Context, *RequestUserModel) (*UserModel, error)
	UpdateUser(context.Context, *RequestUserModel) (*BaseResponse, error)
	DeleteUser(context.Context, *RequestUserModel) (*BaseResponse, error)
}

// UnimplementedUserHandlerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserHandlerServer struct{}

func (UnimplementedUserHandlerServer) GetAllUser(context.Context, *GetAllUserRequest) (*GetAllUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllUser not implemented")
}
func (UnimplementedUserHandlerServer) GetDetailUser(context.Context, *GetDetailUserRequest) (*UserModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetailUser not implemented")
}
func (UnimplementedUserHandlerServer) CreateUser(context.Context, *RequestUserModel) (*UserModel, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserHandlerServer) UpdateUser(context.Context, *RequestUserModel) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserHandlerServer) DeleteUser(context.Context, *RequestUserModel) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserHandlerServer) testEmbeddedByValue() {}

// UnsafeUserHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserHandlerServer will
// result in compilation errors.
type UnsafeUserHandlerServer interface {
	mustEmbedUnimplementedUserHandlerServer()
}

func RegisterUserHandlerServer(s grpc.ServiceRegistrar, srv UserHandlerServer) {
	// If the following call panics, it indicates UnimplementedUserHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserHandler_ServiceDesc, srv)
}

func _UserHandler_GetAllUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).GetAllUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserHandler_GetAllUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).GetAllUser(ctx, req.(*GetAllUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_GetDetailUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).GetDetailUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserHandler_GetDetailUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).GetDetailUser(ctx, req.(*GetDetailUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUserModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserHandler_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).CreateUser(ctx, req.(*RequestUserModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUserModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserHandler_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).UpdateUser(ctx, req.(*RequestUserModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserHandler_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUserModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserHandlerServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserHandler_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserHandlerServer).DeleteUser(ctx, req.(*RequestUserModel))
	}
	return interceptor(ctx, in, info, handler)
}

// UserHandler_ServiceDesc is the grpc.ServiceDesc for UserHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserHandler",
	HandlerType: (*UserHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUser",
			Handler:    _UserHandler_GetAllUser_Handler,
		},
		{
			MethodName: "GetDetailUser",
			Handler:    _UserHandler_GetDetailUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserHandler_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserHandler_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserHandler_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
