// Code generated by candi v1.20.0.

package resthandler

import (
	"encoding/json"
	"io"
	"net/http"

	"monorepo/services/activity/internal/modules/activity/domain"
	"monorepo/services/activity/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	restserver "github.com/golangid/candi/codebase/app/rest_server"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root interfaces.RESTRouter) {
	v1Activity := root.Group(candihelper.V1+"/activity", h.mw.HTTPBearerAuth)

	v1Activity.POST("/", h.saveActivityLog, h.mw.HTTPPermissionACL("saveActivityLog"))
	v1Activity.GET("/", h.getAllActivityLogs, h.mw.HTTPPermissionACL("getAllActivityLogs"))
	v1Activity.GET("/:id", h.getActivityLogByID, h.mw.HTTPPermissionACL("getActivityLogByID"))
}

// saveActivityLog godoc
// @Summary			Save Activity Log
// @Description		Enqueues an activity log entry for async persistence and returns immediately
// @Tags			Activity
// @Accept			json
// @Produce			json
// @Param			data	body	domain.RequestSaveActivity	true	"Body Data"
// @Success			202	{object}	domain.ResponseSaveActivity
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/activity [post]
func (h *RestHandler) saveActivityLog(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "ActivityDeliveryREST:SaveActivityLog")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("activity/save", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	var payload domain.RequestSaveActivity
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	jobID, err := h.uc.Activity().SaveActivityLog(ctx, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusAccepted, "ok", domain.ResponseSaveActivity{JobID: jobID}).JSON(rw)
}

// getAllActivityLogs godoc
// @Summary			Get All Activity Logs
// @Description		API for get all activity logs
// @Tags			Activity
// @Accept			json
// @Produce			json
// @Param			page		query	string	false	"Page with default value is 1"
// @Param			limit		query	string	false	"Limit with default value is 10"
// @Param			search		query	string	false	"Search (matches message)"
// @Param			serviceName	query	string	false	"Filter by service name"
// @Param			referenceId	query	string	false	"Filter by reference id"
// @Param			startDate	query	string	false	"Filter by created_at >= startDate (RFC3339)"
// @Param			endDate		query	string	false	"Filter by created_at <= endDate (RFC3339)"
// @Param			orderBy		query	string	false	"Order By"
// @Param			sort		query	string	false	"Sort (ASC DESC)"
// @Success			200	{object}	domain.ResponseActivityList
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/activity [get]
func (h *RestHandler) getAllActivityLogs(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "ActivityDeliveryREST:GetAllActivityLogs")
	defer trace.Finish()

	var filter domain.FilterActivity
	if err := candihelper.ParseFromQueryParam(req.URL.Query(), &filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(rw)
		return
	}

	if err := h.validator.ValidateDocument("activity/get_all", filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate filter", err).JSON(rw)
		return
	}

	result, err := h.uc.Activity().GetAllActivityLogs(ctx, &filter)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	response := wrapper.NewHTTPResponse(http.StatusOK, "Success", result.Data)
	response.Meta = result.Meta
	response.JSON(rw)
}

// getActivityLogByID godoc
// @Summary			Get Activity Log By ID
// @Description		API for get detail activity log by id
// @Tags			Activity
// @Accept			json
// @Produce			json
// @Param			id	path	string	true	"ID"
// @Success			200	{object}	domain.ResponseActivity
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/activity/{id} [get]
func (h *RestHandler) getActivityLogByID(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "ActivityDeliveryREST:GetActivityLogByID")
	defer trace.Finish()

	id := restserver.URLParam(req, "id")
	data, err := h.uc.Activity().GetActivityLogByID(ctx, id)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Success", data).JSON(rw)
}
