// Code generated by candi v1.20.0.

package workerhandler

import (
	"encoding/json"

	"monorepo/services/notification/internal/modules/notification/domain"
	"monorepo/services/notification/pkg/shared/usecase"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/factory/types"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
)

// KafkaHandler struct
type KafkaHandler struct {
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewKafkaHandler constructor
func NewKafkaHandler(uc usecase.Usecase, deps dependency.Dependency) *KafkaHandler {
	return &KafkaHandler{
		uc:        uc,
		validator: deps.GetValidator(),
	}
}

// MountHandlers mount handler group. Other services publish to
// "notification.requested" with the same payload shape as the REST send
// endpoint (channel/templateCode/recipient/variables) — this keeps
// notification decoupled from needing to understand every producer's own
// event schema.
func (h *KafkaHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("notification.requested", h.handleNotificationRequested)
}

func (h *KafkaHandler) handleNotificationRequested(eventContext *candishared.EventContext) error {
	trace, ctx := tracer.StartTraceWithContext(eventContext.Context(), "NotificationDeliveryKafka:HandleNotificationRequested")
	defer trace.Finish()

	var req domain.RequestSendNotification
	if err := json.Unmarshal(eventContext.Message(), &req); err != nil {
		return err
	}

	_, err := h.uc.Notification().SendNotification(ctx, &req)
	return err
}
