// Code generated by candi v1.20.0. DO NOT EDIT.

package repository

import (
	"go.mongodb.org/mongo-driver/v2/mongo"

	// @candi:repositoryImport
	notificationrepo "monorepo/services/notification/internal/modules/notification/repository"
)

type (
	// RepoMongo abstraction
	RepoMongo interface {
		// @candi:repositoryMethod
		NotificationRepo() notificationrepo.NotificationRepository
	}

	repoMongoImpl struct {
		readDB, writeDB *mongo.Database

		// register all repository from modules
		// @candi:repositoryField
		notificationRepo notificationrepo.NotificationRepository
	}
)

var globalRepoMongo RepoMongo

// setSharedRepoMongo set the global singleton "RepoMongo" implementation
func setSharedRepoMongo(readDB, writeDB *mongo.Database) {
	globalRepoMongo = &repoMongoImpl{
		readDB: readDB, writeDB: writeDB,

		// @candi:repositoryConstructor
		notificationRepo: notificationrepo.NewNotificationRepoMongo(readDB, writeDB),
	}
}

// GetSharedRepoMongo returns the global singleton "RepoMongo" implementation
func GetSharedRepoMongo() RepoMongo {
	return globalRepoMongo
}

// @candi:repositoryImplementation
func (r *repoMongoImpl) NotificationRepo() notificationrepo.NotificationRepository {
	return r.notificationRepo
}
