// Code generated by candi v1.20.0.

package configs

import (
	"context"
	"time"

	"monorepo/globalshared/auth"
	"monorepo/sdk"
	"monorepo/sdk/user"
	"monorepo/services/payment/api"
	"monorepo/services/payment/pkg/shared"
	"monorepo/services/payment/pkg/shared/repository"
	"monorepo/services/payment/pkg/shared/usecase"

	"github.com/golangid/candi/broker"
	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/candiutils"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/config"
	"github.com/golangid/candi/config/database"

	"github.com/golangid/candi/logger"
	"github.com/golangid/candi/middleware"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/validator"
)

// LoadServiceConfigs load selected dependency configuration in this service
func LoadServiceConfigs(baseCfg *config.Config) (deps dependency.Dependency) {
	var sharedEnv shared.Environment
	candihelper.MustParseEnv(&sharedEnv)
	shared.SetEnv(sharedEnv)

	logger.InitZap()
	logger.SetMaskLog(logger.NewMasker("serverKey", "secretKey", "callbackToken", "credentials", "x-callback-token", "x-mock-token"))

	baseCfg.LoadFunc(func(ctx context.Context) []interfaces.Closer {
		otel, _ := tracer.InitOtel(baseCfg.ServiceName)
		// redisDeps := database.InitRedis()
		sqlDeps := database.InitSQLDatabase()
		// mongoDeps := database.InitMongoDB(ctx)

		// permission decisions come from the user service (gRPC), tokens are verified locally through its JWKS
		sdk.SetGlobalSDK(
			sdk.SetUser(user.NewUserServiceGRPC(sharedEnv.UserGRPCHost, sharedEnv.UserBasicAuthKey)),
		)

		locker := &candiutils.NoopLocker{}

		brokerDeps := broker.InitBrokers(
			broker.NewKafkaBroker(),
			// broker.NewRabbitMQBroker(),
			// broker.NewRedisBroker(redisDeps.WritePool()),
		)

		validatorDeps := validator.NewValidator()
		validatorDeps.JSONSchema.SchemaStorage = validator.NewFileSystemStorage(api.JSONSchema, "jsonschema")

		// inject all service dependencies
		// See all option in dependency package
		deps = dependency.InitDependency(
			dependency.SetValidator(validatorDeps),
			dependency.SetBrokers(brokerDeps.GetBrokers()),
			dependency.SetLocker(locker),
			// dependency.SetRedisPool(redisDeps),
			dependency.SetSQLDatabase(sqlDeps),
			// dependency.SetMongoDatabase(mongoDeps),
			// ... add more dependencies
		)
		return []interfaces.Closer{ // throw back to base config for close connection when application shutdown
			otel, deps,
		}
	})

	repository.SetSharedRepository(deps)
	usecase.SetSharedUsecase(deps)

	// REST and gRPC tokens are issued by the user service, see services/user/docs/realms-and-rbac.md
	tokenValidator := auth.NewTokenValidator(sharedEnv.IssuerBaseURL, auth.NewJWKSKeyProvider(sharedEnv.UserHTTPHost))
	aclChecker := auth.NewACLChecker("payment", auth.NewSDKPermissionClient(sdk.GetSDK().User()), 30*time.Second)

	deps.SetMiddleware(middleware.NewMiddlewareWithOption(
		middleware.SetTokenValidator(tokenValidator),
		middleware.SetACLPermissionChecker(aclChecker),
		middleware.SetUserIDExtractor(func(tokenClaim *candishared.TokenClaim) (userID string) {
			return tokenClaim.Subject
		}),
		// middleware.SetCache(deps.GetRedisPool().Cache(), middleware.DefaultCacheAge),
	))

	return deps
}
