// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,3,opt,name=totalRecords,proto3" json:"totalRecords,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Meta) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Meta) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *Meta) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetAllPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	ShowAll       bool                   `protobuf:"varint,6,opt,name=showAll,proto3" json:"showAll,omitempty"`
	StartDate     string                 `protobuf:"bytes,7,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,8,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPaymentRequest) Reset() {
	*x = GetAllPaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPaymentRequest) ProtoMessage() {}

func (x *GetAllPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetAllPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllPaymentRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllPaymentRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllPaymentRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllPaymentRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *GetAllPaymentRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetAllPaymentRequest) GetShowAll() bool {
	if x != nil {
		return x.ShowAll
	}
	return false
}

func (x *GetAllPaymentRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetAllPaymentRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetAllPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []*PaymentModel        `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPaymentResponse) Reset() {
	*x = GetAllPaymentResponse{}
	mi := &file_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPaymentResponse) ProtoMessage() {}

func (x *GetAllPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetAllPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllPaymentResponse) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetAllPaymentResponse) GetData() []*PaymentModel {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDetailPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailPaymentRequest) Reset() {
	*x = GetDetailPaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailPaymentRequest) ProtoMessage() {}

func (x *GetDetailPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetDetailPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetDetailPaymentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestPaymentModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPaymentModel) Reset() {
	*x = RequestPaymentModel{}
	mi := &file_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPaymentModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPaymentModel) ProtoMessage() {}

func (x *RequestPaymentModel) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPaymentModel.ProtoReflect.Descriptor instead.
func (*RequestPaymentModel) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *RequestPaymentModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestPaymentModel) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type PaymentModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentModel) Reset() {
	*x = PaymentModel{}
	mi := &file_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentModel) ProtoMessage() {}

func (x *PaymentModel) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentModel.ProtoReflect.Descriptor instead.
func (*PaymentModel) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentModel) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *PaymentModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_payment_payment_proto protoreflect.FileDescriptor

const file_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x15payment/payment.proto\x12\apayment\"t\n" +
	"\x04Meta\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\"\n" +
	"\ftotalRecords\x18\x03 \x01(\x03R\ftotalRecords\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x04 \x01(\x03R\n" +
	"totalPages\"\xd8\x01\n" +
	"\x14GetAllPaymentRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x18\n" +
	"\aorderBy\x18\x04 \x01(\tR\aorderBy\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x18\n" +
	"\ashowAll\x18\x06 \x01(\bR\ashowAll\x12\x1c\n" +
	"\tstartDate\x18\a \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\b \x01(\tR\aendDate\"e\n" +
	"\x15GetAllPaymentResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.payment.MetaR\x04meta\x12)\n" +
	"\x04data\x18\x02 \x03(\v2\x15.payment.PaymentModelR\x04data\")\n" +
	"\x17GetDetailPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x13RequestPaymentModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"p\n" +
	"\fPaymentModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAt\"(\n" +
	"\fBaseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xff\x02\n" +
	"\x0ePaymentHandler\x12N\n" +
	"\rGetAllPayment\x12\x1d.payment.GetAllPaymentRequest\x1a\x1e.payment.GetAllPaymentResponse\x12K\n" +
	"\x10GetDetailPayment\x12 .payment.GetDetailPaymentRequest\x1a\x15.payment.PaymentModel\x12D\n" +
	"\rCreatePayment\x12\x1c.payment.RequestPaymentModel\x1a\x15.payment.PaymentModel\x12D\n" +
	"\rUpdatePayment\x12\x1c.payment.RequestPaymentModel\x1a\x15.payment.BaseResponse\x12D\n" +
	"\rDeletePayment\x12\x1c.payment.RequestPaymentModel\x1a\x15.payment.BaseResponseB-Z+monorepo/services/payment/api/proto/paymentb\x06proto3"

var (
	file_payment_payment_proto_rawDescOnce sync.Once
	file_payment_payment_proto_rawDescData []byte
)

func file_payment_payment_proto_rawDescGZIP() []byte {
	file_payment_payment_proto_rawDescOnce.Do(func() {
		file_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)))
	})
	return file_payment_payment_proto_rawDescData
}

var file_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_payment_payment_proto_goTypes = []any{
	(*Meta)(nil),                    // 0: payment.Meta
	(*GetAllPaymentRequest)(nil),    // 1: payment.GetAllPaymentRequest
	(*GetAllPaymentResponse)(nil),   // 2: payment.GetAllPaymentResponse
	(*GetDetailPaymentRequest)(nil), // 3: payment.GetDetailPaymentRequest
	(*RequestPaymentModel)(nil),     // 4: payment.RequestPaymentModel
	(*PaymentModel)(nil),            // 5: payment.PaymentModel
	(*BaseResponse)(nil),            // 6: payment.BaseResponse
}
var file_payment_payment_proto_depIdxs = []int32{
	0, // 0: payment.GetAllPaymentResponse.meta:type_name -> payment.Meta
	5, // 1: payment.GetAllPaymentResponse.data:type_name -> payment.PaymentModel
	1, // 2: payment.PaymentHandler.GetAllPayment:input_type -> payment.GetAllPaymentRequest
	3, // 3: payment.PaymentHandler.GetDetailPayment:input_type -> payment.GetDetailPaymentRequest
	4, // 4: payment.PaymentHandler.CreatePayment:input_type -> payment.RequestPaymentModel
	4, // 5: payment.PaymentHandler.UpdatePayment:input_type -> payment.RequestPaymentModel
	4, // 6: payment.PaymentHandler.DeletePayment:input_type -> payment.RequestPaymentModel
	2, // 7: payment.PaymentHandler.GetAllPayment:output_type -> payment.GetAllPaymentResponse
	5, // 8: payment.PaymentHandler.GetDetailPayment:output_type -> payment.PaymentModel
	5, // 9: payment.PaymentHandler.CreatePayment:output_type -> payment.PaymentModel
	6, // 10: payment.PaymentHandler.UpdatePayment:output_type -> payment.BaseResponse
	6, // 11: payment.PaymentHandler.DeletePayment:output_type -> payment.BaseResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_payment_proto_init() }
func file_payment_payment_proto_init() {
	if File_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_payment_proto_goTypes,
		DependencyIndexes: file_payment_payment_proto_depIdxs,
		MessageInfos:      file_payment_payment_proto_msgTypes,
	}.Build()
	File_payment_payment_proto = out.File
	file_payment_payment_proto_goTypes = nil
	file_payment_payment_proto_depIdxs = nil
}
