// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentHandler_CreatePayment_FullMethodName = "/payment.PaymentHandler/CreatePayment"
	PaymentHandler_GetPayment_FullMethodName    = "/payment.PaymentHandler/GetPayment"
	PaymentHandler_CancelPayment_FullMethodName = "/payment.PaymentHandler/CancelPayment"
)

// PaymentHandlerClient is the client API for PaymentHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentHandler is the internal (service-to-service) API of the payment service.
// Other services request a payment link here; the customer then completes the
// checkout through the payment service's REST checkout API.
type PaymentHandlerClient interface {
	// CreatePayment issues a payment link. Idempotent per (source, referenceId) while the payment is open.
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*PaymentModel, error)
	CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*PaymentModel, error)
}

type paymentHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentHandlerClient(cc grpc.ClientConnInterface) PaymentHandlerClient {
	return &paymentHandlerClient{cc}
}

func (c *paymentHandlerClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, PaymentHandler_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentHandlerClient) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*PaymentModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentModel)
	err := c.cc.Invoke(ctx, PaymentHandler_GetPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentHandlerClient) CancelPayment(ctx context.Context, in *CancelPaymentRequest, opts ...grpc.CallOption) (*PaymentModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentModel)
	err := c.cc.Invoke(ctx, PaymentHandler_CancelPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentHandlerServer is the server API for PaymentHandler service.
// All implementations must embed UnimplementedPaymentHandlerServer
// for forward compatibility.
//
// PaymentHandler is the internal (service-to-service) API of the payment service.
// Other services request a payment link here; the customer then completes the
// checkout through the payment service's REST checkout API.
type PaymentHandlerServer interface {
	// CreatePayment issues a payment link. Idempotent per (source, referenceId) while the payment is open.
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	GetPayment(context.Context, *GetPaymentRequest) (*PaymentModel, error)
	CancelPayment(context.Context, *CancelPaymentRequest) (*PaymentModel, error)
	mustEmbedUnimplementedPaymentHandlerServer()
}

// UnimplementedPaymentHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentHandlerServer struct{}

func (UnimplementedPaymentHandlerServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentHandlerServer) GetPayment(context.Context, *GetPaymentRequest) (*PaymentModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedPaymentHandlerServer) CancelPayment(context.Context, *CancelPaymentRequest) (*PaymentModel, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPayment not implemented")
}
func (UnimplementedPaymentHandlerServer) mustEmbedUnimplementedPaymentHandlerServer() {}
func (UnimplementedPaymentHandlerServer) testEmbeddedByValue()                        {}

// UnsafePaymentHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentHandlerServer will
// result in compilation errors.
type UnsafePaymentHandlerServer interface {
	mustEmbedUnimplementedPaymentHandlerServer()
}

func RegisterPaymentHandlerServer(s grpc.ServiceRegistrar, srv PaymentHandlerServer) {
	// If the following call panics, it indicates UnimplementedPaymentHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentHandler_ServiceDesc, srv)
}

func _PaymentHandler_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentHandlerServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentHandler_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentHandlerServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentHandler_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentHandlerServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentHandler_GetPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentHandlerServer).GetPayment(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentHandler_CancelPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentHandlerServer).CancelPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentHandler_CancelPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentHandlerServer).CancelPayment(ctx, req.(*CancelPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentHandler_ServiceDesc is the grpc.ServiceDesc for PaymentHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentHandler",
	HandlerType: (*PaymentHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentHandler_CreatePayment_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _PaymentHandler_GetPayment_Handler,
		},
		{
			MethodName: "CancelPayment",
			Handler:    _PaymentHandler_CancelPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/payment.proto",
}
