// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentHandler_GetAllPayment_FullMethodName    = "/payment.PaymentHandler/GetAllPayment"
	PaymentHandler_GetDetailPayment_FullMethodName = "/payment.PaymentHandler/GetDetailPayment"
	PaymentHandler_CreatePayment_FullMethodName    = "/payment.PaymentHandler/CreatePayment"
	PaymentHandler_UpdatePayment_FullMethodName    = "/payment.PaymentHandler/UpdatePayment"
	PaymentHandler_DeletePayment_FullMethodName    = "/payment.PaymentHandler/DeletePayment"
)

// PaymentHandlerClient is the client API for PaymentHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentHandlerClient interface {
	GetAllPayment(ctx context.Context, in *GetAllPaymentRequest, opts ...grpc.CallOption) (*GetAllPaymentResponse, error)
	GetDetailPayment(ctx context.Context, in *GetDetailPaymentRequest, opts ...grpc.CallOption) (*PaymentModel, error)
	CreatePayment(ctx context.Context, in *RequestPaymentModel, opts ...grpc.CallOption) (*PaymentModel, error)
	UpdatePayment(ctx context.Context, in *RequestPaymentModel, opts ...grpc.CallOption) (*BaseResponse, error)
	DeletePayment(ctx context.Context, in *RequestPaymentModel, opts ...grpc.CallOption) (*BaseResponse, error)
}

type paymentHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentHandlerClient(cc grpc.ClientConnInterface) PaymentHandlerClient {
	return &paymentHandlerClient{cc}
}

func (c *paymentHandlerClient) GetAllPayment(ctx context.Context, in *GetAllPaymentRequest, opts ...grpc.CallOption) (*GetAllPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPaymentResponse)
	err := c.cc.Invoke(ctx, PaymentHandler_GetAllPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentHandlerClient) GetDetailPayment(ctx context.Context, in *GetDetailPaymentRequest, opts ...grpc.CallOption) (*PaymentModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentModel)
	err := c.cc.Invoke(ctx, PaymentHandler_GetDetailPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentHandlerClient) CreatePayment(ctx context.Context, in *RequestPaymentModel, opts ...grpc.CallOption) (*PaymentModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentModel)
	err := c.cc.Invoke(ctx, PaymentHandler_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentHandlerClient) UpdatePayment(ctx context.Context, in *RequestPaymentModel, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PaymentHandler_UpdatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentHandlerClient) DeletePayment(ctx context.Context, in *RequestPaymentModel, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PaymentHandler_DeletePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentHandlerServer is the server API for PaymentHandler service.
// All implementations should embed UnimplementedPaymentHandlerServer
// for forward compatibility.
type PaymentHandlerServer interface {
	GetAllPayment(context.Context, *GetAllPaymentRequest) (*GetAllPaymentResponse, error)
	GetDetailPayment(context.Context, *GetDetailPaymentRequest) (*PaymentModel, error)
	CreatePayment(context.Context, *RequestPaymentModel) (*PaymentModel, error)
	UpdatePayment(context.Context, *RequestPaymentModel) (*BaseResponse, error)
	DeletePayment(context.Context, *RequestPaymentModel) (*BaseResponse, error)
}

// UnimplementedPaymentHandlerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentHandlerServer struct{}

func (UnimplementedPaymentHandlerServer) GetAllPayment(context.Context, *GetAllPaymentRequest) (*GetAllPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPayment not implemented")
}
func (UnimplementedPaymentHandlerServer) GetDetailPayment(context.Context, *GetDetailPaymentRequest) (*PaymentModel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetailPayment not implemented")
}
func (UnimplementedPaymentHandlerServer) CreatePayment(context.Context, *RequestPaymentModel) (*PaymentModel, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentHandlerServer) UpdatePayment(context.Context, *RequestPaymentModel) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePayment not implemented")
}
func (UnimplementedPaymentHandlerServer) DeletePayment(context.Context, *RequestPaymentModel) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePayment not implemented")
}
func (UnimplementedPaymentHandlerServer) testEmbeddedByValue() {}

// UnsafePaymentHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentHandlerServer will
// result in compilation errors.
type UnsafePaymentHandlerServer interface {
	mustEmbedUnimplementedPaymentHandlerServer()
}

func RegisterPaymentHandlerServer(s grpc.ServiceRegistrar, srv PaymentHandlerServer) {
	// If the following call panics, it indicates UnimplementedPaymentHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentHandler_ServiceDesc, srv)
}

func _PaymentHandler_GetAllPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentHandlerServer).GetAllPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentHandler_GetAllPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentHandlerServer).GetAllPayment(ctx, req.(*GetAllPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentHandler_GetDetailPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentHandlerServer).GetDetailPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentHandler_GetDetailPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentHandlerServer).GetDetailPayment(ctx, req.(*GetDetailPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentHandler_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPaymentModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentHandlerServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentHandler_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentHandlerServer).CreatePayment(ctx, req.(*RequestPaymentModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentHandler_UpdatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPaymentModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentHandlerServer).UpdatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentHandler_UpdatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentHandlerServer).UpdatePayment(ctx, req.(*RequestPaymentModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentHandler_DeletePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPaymentModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentHandlerServer).DeletePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentHandler_DeletePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentHandlerServer).DeletePayment(ctx, req.(*RequestPaymentModel))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentHandler_ServiceDesc is the grpc.ServiceDesc for PaymentHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentHandler",
	HandlerType: (*PaymentHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllPayment",
			Handler:    _PaymentHandler_GetAllPayment_Handler,
		},
		{
			MethodName: "GetDetailPayment",
			Handler:    _PaymentHandler_GetDetailPayment_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentHandler_CreatePayment_Handler,
		},
		{
			MethodName: "UpdatePayment",
			Handler:    _PaymentHandler_UpdatePayment_Handler,
		},
		{
			MethodName: "DeletePayment",
			Handler:    _PaymentHandler_DeletePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/payment.proto",
}
