// Code generated by candi v1.20.0.

package workerhandler

import (
	"encoding/json"
	"time"

	"monorepo/services/activity/internal/modules/activity/domain"
	"monorepo/services/activity/pkg/shared/usecase"

	"github.com/golangid/candi/candishared"
	taskqueueworker "github.com/golangid/candi/codebase/app/task_queue_worker"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/factory/types"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
)

// TaskQueueHandler struct
type TaskQueueHandler struct {
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewTaskQueueHandler constructor
func NewTaskQueueHandler(uc usecase.Usecase, deps dependency.Dependency) *TaskQueueHandler {
	return &TaskQueueHandler{
		uc:        uc,
		validator: deps.GetValidator(),
	}
}

// MountHandlers mount handler group
func (h *TaskQueueHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add(domain.TaskNameActivity, h.handleTaskActivity,
		types.WorkerHandlerOptionAddConfig(taskqueueworker.TaskOptionDeleteJobAfterSuccess, false),
	)
}

func (h *TaskQueueHandler) handleTaskActivity(eventContext *candishared.EventContext) error {
	trace, ctx := tracer.StartTraceWithContext(eventContext.Context(), "ActivityDeliveryTaskQueue:HandleTaskActivity")
	defer trace.Finish()

	var payload domain.RequestSaveActivity
	if err := json.Unmarshal(eventContext.Message(), &payload); err != nil {
		return err // bad payload, non-retriable
	}

	if err := h.uc.Activity().PersistActivityLog(ctx, &payload); err != nil {
		return &candishared.ErrorRetrier{
			Delay:   2 * time.Second,
			Message: "failed to persist activity log, retrying: " + err.Error(),
		}
	}
	return nil
}
