// Code generated by candi v1.20.0.

package shared

// Environment additional in this service
type Environment struct {
	SMTPHost        string `env:"SMTP_HOST"`
	SMTPPort        int    `env:"SMTP_PORT"`
	SMTPUsername    string `env:"SMTP_USERNAME"`
	SMTPPassword    string `env:"SMTP_PASSWORD"`
	SMTPFromAddress string `env:"SMTP_FROM_ADDRESS"`
	SMTPFromName    string `env:"SMTP_FROM_NAME"`

	FCMCredentialsJSONPath string `env:"FCM_CREDENTIALS_JSON_PATH"`
}

var sharedEnv Environment

// GetEnv get global additional environment
func GetEnv() Environment {
	return sharedEnv
}

// SetEnv get global additional environment
func SetEnv(env Environment) {
	sharedEnv = env
}
