// Code generated by candi v1.20.0.

package configs

import (
	"context"

	"monorepo/sdk"
	"monorepo/sdk/notification"
	"monorepo/services/user/api"
	"monorepo/services/user/pkg/shared"
	sharedmw "monorepo/services/user/pkg/shared/middleware"
	"monorepo/services/user/pkg/shared/repository"
	"monorepo/services/user/pkg/shared/usecase"

	"github.com/golangid/candi/broker"
	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/candiutils"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/config"
	"github.com/golangid/candi/config/database"

	"github.com/golangid/candi/logger"
	"github.com/golangid/candi/middleware"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/validator"
)

// LoadServiceConfigs load selected dependency configuration in this service
func LoadServiceConfigs(baseCfg *config.Config) (deps dependency.Dependency) {
	var sharedEnv shared.Environment
	candihelper.MustParseEnv(&sharedEnv)
	shared.SetEnv(sharedEnv)

	logger.InitZap()
	logger.SetMaskLog(logger.NewMasker("password", "refreshToken", "accessToken", "clientSecret"))

	baseCfg.LoadFunc(func(ctx context.Context) []interfaces.Closer {
		otel, _ := tracer.InitOtel(baseCfg.ServiceName)
		// redisDeps := database.InitRedis()
		sqlDeps := database.InitSQLDatabase()
		// mongoDeps := database.InitMongoDB(ctx)

		// OTP login goes through the notification service, it is optional
		var sdkOptions []sdk.Option
		if sharedEnv.NotificationHost != "" {
			sdkOptions = append(sdkOptions, sdk.SetNotification(
				notification.NewNotificationServiceREST(sharedEnv.NotificationHost, sharedEnv.NotificationAuthKey),
			))
		}
		sdk.SetGlobalSDK(sdkOptions...)

		locker := &candiutils.NoopLocker{}

		brokerDeps := broker.InitBrokers(
		// broker.NewKafkaBroker(),
		// broker.NewRabbitMQBroker(),
		// broker.NewRedisBroker(redisDeps.WritePool()),
		)

		validatorDeps := validator.NewValidator()
		validatorDeps.JSONSchema.SchemaStorage = validator.NewFileSystemStorage(api.JSONSchema, "jsonschema")

		// inject all service dependencies
		// See all option in dependency package
		deps = dependency.InitDependency(
			dependency.SetValidator(validatorDeps),
			dependency.SetBrokers(brokerDeps.GetBrokers()),
			dependency.SetLocker(locker),
			// dependency.SetRedisPool(redisDeps),
			dependency.SetSQLDatabase(sqlDeps),
			// dependency.SetMongoDatabase(mongoDeps),
			// ... add more dependencies
		)
		return []interfaces.Closer{ // throw back to base config for close connection when application shutdown
			otel, deps,
		}
	})

	repository.SetSharedRepository(deps)
	usecase.SetSharedUsecase(deps)

	deps.SetMiddleware(middleware.NewMiddlewareWithOption(
		middleware.SetTokenValidator(sharedmw.NewTokenValidator()),
		middleware.SetACLPermissionChecker(sharedmw.NewACLChecker()),
		middleware.SetUserIDExtractor(func(tokenClaim *candishared.TokenClaim) (userID string) {
			return tokenClaim.Subject
		}),
		// middleware.SetCache(deps.GetRedisPool().Cache(), middleware.DefaultCacheAge),
	))

	return deps
}
