// Code generated by candi v1.20.0.

package resthandler

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"monorepo/services/notification/internal/modules/notification/domain"
	mockusecase "monorepo/services/notification/pkg/mocks/modules/notification/usecase"
	mocksharedusecase "monorepo/services/notification/pkg/mocks/shared/usecase"

	"github.com/golangid/candi/candihelper"
	mockdeps "github.com/golangid/candi/mocks/codebase/factory/dependency"
	mockinterfaces "github.com/golangid/candi/mocks/codebase/interfaces"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

type testCase struct {
	name, reqBody string
	wantUcError   error
	wantRespCode  int
}

var errFoo = errors.New("Something error")

func TestNewRestHandler(t *testing.T) {
	mockMiddleware := &mockinterfaces.Middleware{}
	mockMiddleware.On("HTTPPermissionACL", mock.Anything).Return(func(http.Handler) http.Handler { return nil })
	mockValidator := &mockinterfaces.Validator{}

	mockDeps := &mockdeps.Dependency{}
	mockDeps.On("GetMiddleware").Return(mockMiddleware)
	mockDeps.On("GetValidator").Return(mockValidator)

	handler := NewRestHandler(nil, mockDeps)
	assert.NotNil(t, handler)

	mockRoute := &mockinterfaces.RESTRouter{}
	mockRoute.On("Group", mock.Anything, mock.Anything).Return(mockRoute)
	mockRoute.On("GET", mock.Anything, mock.Anything, mock.Anything)
	mockRoute.On("POST", mock.Anything, mock.Anything, mock.Anything)
	mockRoute.On("PUT", mock.Anything, mock.Anything, mock.Anything)
	mockRoute.On("DELETE", mock.Anything, mock.Anything, mock.Anything)
	handler.Mount(mockRoute)
}

func newHandler(activityUsecase *mockusecase.NotificationUsecase, validator *mockinterfaces.Validator) RestHandler {
	uc := &mocksharedusecase.Usecase{}
	uc.On("Notification").Return(activityUsecase)
	return RestHandler{uc: uc, validator: validator}
}

func TestRestHandler_sendNotification(t *testing.T) {
	tests := []testCase{
		{name: "Positive", reqBody: `{"channel":"email","templateCode":"otp_verification","recipient":"a@b.com"}`, wantRespCode: http.StatusAccepted},
		{name: "Negative invalid json", reqBody: `{`, wantRespCode: http.StatusBadRequest},
		{name: "Negative usecase error", reqBody: `{"channel":"email"}`, wantUcError: errFoo, wantRespCode: http.StatusBadRequest},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			uc := &mockusecase.NotificationUsecase{}
			uc.On("SendNotification", mock.Anything, mock.Anything).Return("job-id", tt.wantUcError)
			mockValidator := &mockinterfaces.Validator{}
			mockValidator.On("ValidateDocument", mock.Anything, mock.Anything).Return(nil)

			handler := newHandler(uc, mockValidator)
			req := httptest.NewRequest(http.MethodPost, "/", strings.NewReader(tt.reqBody))
			req.Header.Add(candihelper.HeaderContentType, candihelper.HeaderMIMEApplicationJSON)
			res := httptest.NewRecorder()
			handler.sendNotification(res, req)
			assert.Equal(t, tt.wantRespCode, res.Code)
		})
	}
}

func TestRestHandler_getAllNotificationLogs(t *testing.T) {
	uc := &mockusecase.NotificationUsecase{}
	uc.On("GetAllNotificationLogs", mock.Anything, mock.Anything).Return(domain.ResponseNotificationLogList{}, nil)
	mockValidator := &mockinterfaces.Validator{}
	mockValidator.On("ValidateDocument", mock.Anything, mock.Anything).Return(nil)
	handler := newHandler(uc, mockValidator)

	req := httptest.NewRequest(http.MethodGet, "/", nil)
	res := httptest.NewRecorder()
	handler.getAllNotificationLogs(res, req)
	assert.Equal(t, http.StatusOK, res.Code)
}

func TestRestHandler_getNotificationLogByID(t *testing.T) {
	tests := []testCase{
		{name: "Positive", wantRespCode: http.StatusOK},
		{name: "Negative", wantUcError: errFoo, wantRespCode: http.StatusBadRequest},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			uc := &mockusecase.NotificationUsecase{}
			uc.On("GetNotificationLogByID", mock.Anything, mock.Anything).Return(domain.ResponseNotificationLog{}, tt.wantUcError)
			handler := newHandler(uc, &mockinterfaces.Validator{})

			req := httptest.NewRequest(http.MethodGet, "/", nil)
			res := httptest.NewRecorder()
			handler.getNotificationLogByID(res, req)
			assert.Equal(t, tt.wantRespCode, res.Code)
		})
	}
}

func TestRestHandler_getAllTemplates(t *testing.T) {
	uc := &mockusecase.NotificationUsecase{}
	uc.On("GetAllTemplates", mock.Anything, mock.Anything).Return(domain.ResponseTemplateList{}, nil)
	handler := newHandler(uc, &mockinterfaces.Validator{})

	req := httptest.NewRequest(http.MethodGet, "/", nil)
	res := httptest.NewRecorder()
	handler.getAllTemplates(res, req)
	assert.Equal(t, http.StatusOK, res.Code)
}

func TestRestHandler_createTemplate(t *testing.T) {
	tests := []testCase{
		{name: "Positive", reqBody: `{"code":"otp_verification","channel":"email","bodyTemplate":"hi {{.code}}","isActive":true}`, wantRespCode: http.StatusCreated},
		{name: "Negative invalid json", reqBody: `{`, wantRespCode: http.StatusBadRequest},
		{name: "Negative usecase error", reqBody: `{}`, wantUcError: errFoo, wantRespCode: http.StatusBadRequest},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			uc := &mockusecase.NotificationUsecase{}
			uc.On("CreateTemplate", mock.Anything, mock.Anything).Return(domain.ResponseTemplate{}, tt.wantUcError)
			handler := newHandler(uc, &mockinterfaces.Validator{})

			req := httptest.NewRequest(http.MethodPost, "/", strings.NewReader(tt.reqBody))
			res := httptest.NewRecorder()
			handler.createTemplate(res, req)
			assert.Equal(t, tt.wantRespCode, res.Code)
		})
	}
}

func TestRestHandler_updateTemplate(t *testing.T) {
	uc := &mockusecase.NotificationUsecase{}
	uc.On("UpdateTemplate", mock.Anything, mock.Anything, mock.Anything).Return(domain.ResponseTemplate{}, nil)
	handler := newHandler(uc, &mockinterfaces.Validator{})

	req := httptest.NewRequest(http.MethodPut, "/", strings.NewReader(`{"code":"x","channel":"email","bodyTemplate":"y","isActive":true}`))
	res := httptest.NewRecorder()
	handler.updateTemplate(res, req)
	assert.Equal(t, http.StatusOK, res.Code)
}

func TestRestHandler_deleteTemplate(t *testing.T) {
	tests := []testCase{
		{name: "Positive", wantRespCode: http.StatusOK},
		{name: "Negative", wantUcError: errFoo, wantRespCode: http.StatusBadRequest},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			uc := &mockusecase.NotificationUsecase{}
			uc.On("DeleteTemplate", mock.Anything, mock.Anything).Return(tt.wantUcError)
			handler := newHandler(uc, &mockinterfaces.Validator{})

			req := httptest.NewRequest(http.MethodDelete, "/", nil)
			res := httptest.NewRecorder()
			handler.deleteTemplate(res, req)
			assert.Equal(t, tt.wantRespCode, res.Code)
		})
	}
}

func TestRestHandler_getChannelConfig(t *testing.T) {
	uc := &mockusecase.NotificationUsecase{}
	uc.On("GetChannelConfig", mock.Anything, mock.Anything).Return(domain.ResponseChannelConfig{}, nil)
	handler := newHandler(uc, &mockinterfaces.Validator{})

	req := httptest.NewRequest(http.MethodGet, "/", nil)
	res := httptest.NewRecorder()
	handler.getChannelConfig(res, req)
	assert.Equal(t, http.StatusOK, res.Code)
}

func TestRestHandler_updateChannelConfig(t *testing.T) {
	tests := []testCase{
		{name: "Positive", reqBody: `{"isEnabled":true}`, wantRespCode: http.StatusOK},
		{name: "Negative invalid json", reqBody: `{`, wantRespCode: http.StatusBadRequest},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			uc := &mockusecase.NotificationUsecase{}
			uc.On("UpdateChannelConfig", mock.Anything, mock.Anything, mock.Anything).Return(domain.ResponseChannelConfig{}, nil)
			handler := newHandler(uc, &mockinterfaces.Validator{})

			req := httptest.NewRequest(http.MethodPut, "/", strings.NewReader(tt.reqBody))
			res := httptest.NewRecorder()
			handler.updateChannelConfig(res, req)
			assert.Equal(t, tt.wantRespCode, res.Code)
		})
	}
}
