// Code generated by candi v1.20.0.

package resthandler

import (
	"encoding/json"
	"io"
	"net/http"
	"strconv"

	"monorepo/services/notification/internal/modules/notification/domain"
	"monorepo/services/notification/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	restserver "github.com/golangid/candi/codebase/app/rest_server"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
func (h *RestHandler) Mount(root interfaces.RESTRouter) {
	v1Notification := root.Group(candihelper.V1+"/notification", h.mw.HTTPBearerAuth)

	v1Notification.POST("/send", h.sendNotification, h.mw.HTTPPermissionACL("sendNotification"))
	v1Notification.GET("/logs", h.getAllNotificationLogs, h.mw.HTTPPermissionACL("getAllNotificationLogs"))
	v1Notification.GET("/logs/:id", h.getNotificationLogByID, h.mw.HTTPPermissionACL("getNotificationLogByID"))
	v1Notification.GET("/templates", h.getAllTemplates, h.mw.HTTPPermissionACL("getAllTemplates"))
	v1Notification.POST("/templates", h.createTemplate, h.mw.HTTPPermissionACL("createTemplate"))
	v1Notification.PUT("/templates/:id", h.updateTemplate, h.mw.HTTPPermissionACL("updateTemplate"))
	v1Notification.DELETE("/templates/:id", h.deleteTemplate, h.mw.HTTPPermissionACL("deleteTemplate"))
	v1Notification.GET("/channel-configs/:channel", h.getChannelConfig, h.mw.HTTPPermissionACL("getChannelConfig"))
	v1Notification.PUT("/channel-configs/:channel", h.updateChannelConfig, h.mw.HTTPPermissionACL("updateChannelConfig"))
}

// sendNotification godoc
// @Summary			Send Notification
// @Description		Renders the template and enqueues async dispatch, returns immediately
// @Tags			Notification
// @Accept			json
// @Produce			json
// @Param			data	body	domain.RequestSendNotification	true	"Body Data"
// @Success			202	{object}	domain.ResponseSendNotification
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/notification/send [post]
func (h *RestHandler) sendNotification(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "NotificationDeliveryREST:SendNotification")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("notification/save", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	var payload domain.RequestSendNotification
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	jobID, err := h.uc.Notification().SendNotification(ctx, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusAccepted, "ok", domain.ResponseSendNotification{JobID: jobID}).JSON(rw)
}

// getAllNotificationLogs godoc
// @Summary			Get All Notification Logs
// @Tags			Notification
// @Accept			json
// @Produce			json
// @Param			page			query	string	false	"Page with default value is 1"
// @Param			limit			query	string	false	"Limit with default value is 10"
// @Param			channel			query	string	false	"Filter by channel"
// @Param			templateCode	query	string	false	"Filter by template code"
// @Param			recipient		query	string	false	"Filter by recipient"
// @Param			status			query	string	false	"Filter by status"
// @Success			200	{object}	domain.ResponseNotificationLogList
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/notification/logs [get]
func (h *RestHandler) getAllNotificationLogs(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "NotificationDeliveryREST:GetAllNotificationLogs")
	defer trace.Finish()

	var filter domain.FilterNotificationLog
	if err := candihelper.ParseFromQueryParam(req.URL.Query(), &filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(rw)
		return
	}

	if err := h.validator.ValidateDocument("notification/get_all", filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate filter", err).JSON(rw)
		return
	}

	result, err := h.uc.Notification().GetAllNotificationLogs(ctx, &filter)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	response := wrapper.NewHTTPResponse(http.StatusOK, "Success", result.Data)
	response.Meta = result.Meta
	response.JSON(rw)
}

// getNotificationLogByID godoc
// @Summary			Get Notification Log By ID
// @Tags			Notification
// @Accept			json
// @Produce			json
// @Param			id	path	string	true	"ID"
// @Success			200	{object}	domain.ResponseNotificationLog
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/notification/logs/{id} [get]
func (h *RestHandler) getNotificationLogByID(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "NotificationDeliveryREST:GetNotificationLogByID")
	defer trace.Finish()

	id, _ := strconv.Atoi(restserver.URLParam(req, "id"))
	data, err := h.uc.Notification().GetNotificationLogByID(ctx, id)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Success", data).JSON(rw)
}

// getAllTemplates godoc
// @Summary			Get All Templates
// @Tags			Notification
// @Accept			json
// @Produce			json
// @Param			page		query	string	false	"Page with default value is 1"
// @Param			limit		query	string	false	"Limit with default value is 10"
// @Param			channel		query	string	false	"Filter by channel"
// @Success			200	{object}	domain.ResponseTemplateList
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/notification/templates [get]
func (h *RestHandler) getAllTemplates(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "NotificationDeliveryREST:GetAllTemplates")
	defer trace.Finish()

	var filter domain.FilterTemplate
	if err := candihelper.ParseFromQueryParam(req.URL.Query(), &filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(rw)
		return
	}

	result, err := h.uc.Notification().GetAllTemplates(ctx, &filter)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	response := wrapper.NewHTTPResponse(http.StatusOK, "Success", result.Data)
	response.Meta = result.Meta
	response.JSON(rw)
}

// createTemplate godoc
// @Summary			Create Template
// @Tags			Notification
// @Accept			json
// @Produce			json
// @Param			data	body	domain.RequestUpsertTemplate	true	"Body Data"
// @Success			200	{object}	domain.ResponseTemplate
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/notification/templates [post]
func (h *RestHandler) createTemplate(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "NotificationDeliveryREST:CreateTemplate")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	var payload domain.RequestUpsertTemplate
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	res, err := h.uc.Notification().CreateTemplate(ctx, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusCreated, "Success", res).JSON(rw)
}

// updateTemplate godoc
// @Summary			Update Template
// @Tags			Notification
// @Accept			json
// @Produce			json
// @Param			id		path	string	true	"ID"
// @Param			data	body	domain.RequestUpsertTemplate	true	"Body Data"
// @Success			200	{object}	domain.ResponseTemplate
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/notification/templates/{id} [put]
func (h *RestHandler) updateTemplate(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "NotificationDeliveryREST:UpdateTemplate")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	var payload domain.RequestUpsertTemplate
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	id, _ := strconv.Atoi(restserver.URLParam(req, "id"))
	res, err := h.uc.Notification().UpdateTemplate(ctx, id, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Success", res).JSON(rw)
}

// deleteTemplate godoc
// @Summary			Delete Template
// @Tags			Notification
// @Accept			json
// @Produce			json
// @Param			id	path	string	true	"ID"
// @Success			200	{object}	wrapper.HTTPResponse
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/notification/templates/{id} [delete]
func (h *RestHandler) deleteTemplate(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "NotificationDeliveryREST:DeleteTemplate")
	defer trace.Finish()

	id, _ := strconv.Atoi(restserver.URLParam(req, "id"))
	if err := h.uc.Notification().DeleteTemplate(ctx, id); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(rw)
}

// getChannelConfig godoc
// @Summary			Get Channel Config
// @Tags			Notification
// @Accept			json
// @Produce			json
// @Param			channel	path	string	true	"Channel (email|push)"
// @Success			200	{object}	domain.ResponseChannelConfig
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/notification/channel-configs/{channel} [get]
func (h *RestHandler) getChannelConfig(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "NotificationDeliveryREST:GetChannelConfig")
	defer trace.Finish()

	channel := restserver.URLParam(req, "channel")
	data, err := h.uc.Notification().GetChannelConfig(ctx, channel)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Success", data).JSON(rw)
}

// updateChannelConfig godoc
// @Summary			Update Channel Config
// @Tags			Notification
// @Accept			json
// @Produce			json
// @Param			channel	path	string	true	"Channel (email|push)"
// @Param			data	body	domain.RequestUpsertChannelConfig	true	"Body Data"
// @Success			200	{object}	domain.ResponseChannelConfig
// @Success			400	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/notification/channel-configs/{channel} [put]
func (h *RestHandler) updateChannelConfig(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "NotificationDeliveryREST:UpdateChannelConfig")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	var payload domain.RequestUpsertChannelConfig
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	channel := restserver.URLParam(req, "channel")
	res, err := h.uc.Notification().UpdateChannelConfig(ctx, channel, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Success", res).JSON(rw)
}
