// Code generated by candi v1.20.0.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	shipmentusecase "monorepo/services/shipment/internal/modules/shipment/usecase"
	"monorepo/services/shipment/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		Shipment() shipmentusecase.ShipmentUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		shipmentusecase.ShipmentUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.ShipmentUsecase, setSharedUsecaseFunc = shipmentusecase.NewShipmentUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) Shipment() shipmentusecase.ShipmentUsecase {
	return uc.ShipmentUsecase
}
